// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main/proto/compile.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package main.proto;

@kotlin.jvm.JvmName("-initializecompileDiagnosticNote")
public inline fun compileDiagnosticNote(block: main.proto.CompileDiagnosticNoteKt.Dsl.() -> kotlin.Unit): main.proto.Compile.CompileDiagnosticNote =
  main.proto.CompileDiagnosticNoteKt.Dsl._create(main.proto.Compile.CompileDiagnosticNote.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `main.proto.CompileDiagnosticNote`
 */
public object CompileDiagnosticNoteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: main.proto.Compile.CompileDiagnosticNote.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: main.proto.Compile.CompileDiagnosticNote.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): main.proto.Compile.CompileDiagnosticNote = _builder.build()

    /**
     * ```
     * The message describing the compiler note.
     * ```
     *
     * `string message = 1;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * The message describing the compiler note.
     * ```
     *
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * The file of the compiler note.
     * ```
     *
     * `string file = 2;`
     */
    public var file: kotlin.String
      @kotlin.jvm.JvmName("getFile")
        get() = _builder.file
      @kotlin.jvm.JvmName("setFile")
        set(value) {
        _builder.file = value
      }
    /**
     * ```
     * The file of the compiler note.
     * ```
     *
     * `string file = 2;`
     */
    public fun clearFile() {
      _builder.clearFile()
    }

    /**
     * ```
     * The line of the compiler note.
     * ```
     *
     * `int64 line = 3;`
     */
    public var line: kotlin.Long
      @kotlin.jvm.JvmName("getLine")
        get() = _builder.line
      @kotlin.jvm.JvmName("setLine")
        set(value) {
        _builder.line = value
      }
    /**
     * ```
     * The line of the compiler note.
     * ```
     *
     * `int64 line = 3;`
     */
    public fun clearLine() {
      _builder.clearLine()
    }

    /**
     * ```
     * The column of the compiler note.
     * ```
     *
     * `int64 column = 4;`
     */
    public var column: kotlin.Long
      @kotlin.jvm.JvmName("getColumn")
        get() = _builder.column
      @kotlin.jvm.JvmName("setColumn")
        set(value) {
        _builder.column = value
      }
    /**
     * ```
     * The column of the compiler note.
     * ```
     *
     * `int64 column = 4;`
     */
    public fun clearColumn() {
      _builder.clearColumn()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun main.proto.Compile.CompileDiagnosticNote.copy(block: `main.proto`.CompileDiagnosticNoteKt.Dsl.() -> kotlin.Unit): main.proto.Compile.CompileDiagnosticNote =
  `main.proto`.CompileDiagnosticNoteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

