// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main/proto/lib.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package main.proto;

@kotlin.jvm.JvmName("-initializelibrarySearchRequest")
public inline fun librarySearchRequest(block: main.proto.LibrarySearchRequestKt.Dsl.() -> kotlin.Unit): main.proto.Lib.LibrarySearchRequest =
  main.proto.LibrarySearchRequestKt.Dsl._create(main.proto.Lib.LibrarySearchRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `main.proto.LibrarySearchRequest`
 */
public object LibrarySearchRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: main.proto.Lib.LibrarySearchRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: main.proto.Lib.LibrarySearchRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): main.proto.Lib.LibrarySearchRequest = _builder.build()

    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.main.proto.Instance instance = 1;`
     */
    public var instance: main.proto.Common.Instance
      @kotlin.jvm.JvmName("getInstance")
        get() = _builder.instance
      @kotlin.jvm.JvmName("setInstance")
        set(value) {
        _builder.instance = value
      }
    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.main.proto.Instance instance = 1;`
     */
    public fun clearInstance() {
      _builder.clearInstance()
    }
    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.main.proto.Instance instance = 1;`
     * @return Whether the instance field is set.
     */
    public fun hasInstance(): kotlin.Boolean {
      return _builder.hasInstance()
    }

    public val LibrarySearchRequestKt.Dsl.instanceOrNull: main.proto.Common.Instance?
      get() = _builder.instanceOrNull

    /**
     * ```
     * Set to true to not populate the releases field in the response (may save a
     * lot of bandwidth/CPU).
     * ```
     *
     * `bool omit_releases_details = 2;`
     */
    public var omitReleasesDetails: kotlin.Boolean
      @kotlin.jvm.JvmName("getOmitReleasesDetails")
        get() = _builder.omitReleasesDetails
      @kotlin.jvm.JvmName("setOmitReleasesDetails")
        set(value) {
        _builder.omitReleasesDetails = value
      }
    /**
     * ```
     * Set to true to not populate the releases field in the response (may save a
     * lot of bandwidth/CPU).
     * ```
     *
     * `bool omit_releases_details = 2;`
     */
    public fun clearOmitReleasesDetails() {
      _builder.clearOmitReleasesDetails()
    }

    /**
     * ```
     * Keywords for the search.
     * ```
     *
     * `string search_args = 3;`
     */
    public var searchArgs: kotlin.String
      @kotlin.jvm.JvmName("getSearchArgs")
        get() = _builder.searchArgs
      @kotlin.jvm.JvmName("setSearchArgs")
        set(value) {
        _builder.searchArgs = value
      }
    /**
     * ```
     * Keywords for the search.
     * ```
     *
     * `string search_args = 3;`
     */
    public fun clearSearchArgs() {
      _builder.clearSearchArgs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun main.proto.Lib.LibrarySearchRequest.copy(block: `main.proto`.LibrarySearchRequestKt.Dsl.() -> kotlin.Unit): main.proto.Lib.LibrarySearchRequest =
  `main.proto`.LibrarySearchRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val main.proto.Lib.LibrarySearchRequestOrBuilder.instanceOrNull: main.proto.Common.Instance?
  get() = if (hasInstance()) getInstance() else null

