// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main/proto/lib.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package main.proto;

@kotlin.jvm.JvmName("-initializelibraryInstallResponse")
public inline fun libraryInstallResponse(block: main.proto.LibraryInstallResponseKt.Dsl.() -> kotlin.Unit): main.proto.Lib.LibraryInstallResponse =
  main.proto.LibraryInstallResponseKt.Dsl._create(main.proto.Lib.LibraryInstallResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `main.proto.LibraryInstallResponse`
 */
public object LibraryInstallResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: main.proto.Lib.LibraryInstallResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: main.proto.Lib.LibraryInstallResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): main.proto.Lib.LibraryInstallResponse = _builder.build()

    /**
     * ```
     * Progress of the library download.
     * ```
     *
     * `.main.proto.DownloadProgress progress = 1;`
     */
    public var progress: main.proto.Common.DownloadProgress
      @kotlin.jvm.JvmName("getProgress")
        get() = _builder.progress
      @kotlin.jvm.JvmName("setProgress")
        set(value) {
        _builder.progress = value
      }
    /**
     * ```
     * Progress of the library download.
     * ```
     *
     * `.main.proto.DownloadProgress progress = 1;`
     */
    public fun clearProgress() {
      _builder.clearProgress()
    }
    /**
     * ```
     * Progress of the library download.
     * ```
     *
     * `.main.proto.DownloadProgress progress = 1;`
     * @return Whether the progress field is set.
     */
    public fun hasProgress(): kotlin.Boolean {
      return _builder.hasProgress()
    }

    /**
     * ```
     * Description of the current stage of the installation.
     * ```
     *
     * `.main.proto.TaskProgress task_progress = 2;`
     */
    public var taskProgress: main.proto.Common.TaskProgress
      @kotlin.jvm.JvmName("getTaskProgress")
        get() = _builder.taskProgress
      @kotlin.jvm.JvmName("setTaskProgress")
        set(value) {
        _builder.taskProgress = value
      }
    /**
     * ```
     * Description of the current stage of the installation.
     * ```
     *
     * `.main.proto.TaskProgress task_progress = 2;`
     */
    public fun clearTaskProgress() {
      _builder.clearTaskProgress()
    }
    /**
     * ```
     * Description of the current stage of the installation.
     * ```
     *
     * `.main.proto.TaskProgress task_progress = 2;`
     * @return Whether the taskProgress field is set.
     */
    public fun hasTaskProgress(): kotlin.Boolean {
      return _builder.hasTaskProgress()
    }

    /**
     * ```
     * Download result.
     * ```
     *
     * `.main.proto.LibraryInstallResponse.Result result = 3;`
     */
    public var result: main.proto.Lib.LibraryInstallResponse.Result
      @kotlin.jvm.JvmName("getResult")
        get() = _builder.result
      @kotlin.jvm.JvmName("setResult")
        set(value) {
        _builder.result = value
      }
    /**
     * ```
     * Download result.
     * ```
     *
     * `.main.proto.LibraryInstallResponse.Result result = 3;`
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * ```
     * Download result.
     * ```
     *
     * `.main.proto.LibraryInstallResponse.Result result = 3;`
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }
    public val messageCase: main.proto.Lib.LibraryInstallResponse.MessageCase
    @kotlin.jvm.JvmName("getMessageCase")
      get() = _builder.getMessageCase()

    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
  @kotlin.jvm.JvmName("-initializeresult")
  public inline fun result(block: main.proto.LibraryInstallResponseKt.ResultKt.Dsl.() -> kotlin.Unit): main.proto.Lib.LibraryInstallResponse.Result =
    main.proto.LibraryInstallResponseKt.ResultKt.Dsl._create(main.proto.Lib.LibraryInstallResponse.Result.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Empty message, reserved for future expansion.
   * ```
   *
   * Protobuf type `main.proto.LibraryInstallResponse.Result`
   */
  public object ResultKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: main.proto.Lib.LibraryInstallResponse.Result.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: main.proto.Lib.LibraryInstallResponse.Result.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): main.proto.Lib.LibraryInstallResponse.Result = _builder.build()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun main.proto.Lib.LibraryInstallResponse.copy(block: `main.proto`.LibraryInstallResponseKt.Dsl.() -> kotlin.Unit): main.proto.Lib.LibraryInstallResponse =
  `main.proto`.LibraryInstallResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun main.proto.Lib.LibraryInstallResponse.Result.copy(block: `main.proto`.LibraryInstallResponseKt.ResultKt.Dsl.() -> kotlin.Unit): main.proto.Lib.LibraryInstallResponse.Result =
  `main.proto`.LibraryInstallResponseKt.ResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val main.proto.Lib.LibraryInstallResponseOrBuilder.progressOrNull: main.proto.Common.DownloadProgress?
  get() = if (hasProgress()) getProgress() else null

public val main.proto.Lib.LibraryInstallResponseOrBuilder.taskProgressOrNull: main.proto.Common.TaskProgress?
  get() = if (hasTaskProgress()) getTaskProgress() else null

public val main.proto.Lib.LibraryInstallResponseOrBuilder.resultOrNull: main.proto.Lib.LibraryInstallResponse.Result?
  get() = if (hasResult()) getResult() else null

