// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main/proto/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package main.proto;

@kotlin.jvm.JvmName("-initializemissingProgrammerError")
public inline fun missingProgrammerError(block: main.proto.MissingProgrammerErrorKt.Dsl.() -> kotlin.Unit): main.proto.Common.MissingProgrammerError =
  main.proto.MissingProgrammerErrorKt.Dsl._create(main.proto.Common.MissingProgrammerError.newBuilder()).apply { block() }._build()
/**
 * ```
 * MissingProgrammerError is a status error detail that is returned when
 * the operation can not be completed due to a missing programmer argument.
 * ```
 *
 * Protobuf type `main.proto.MissingProgrammerError`
 */
public object MissingProgrammerErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: main.proto.Common.MissingProgrammerError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: main.proto.Common.MissingProgrammerError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): main.proto.Common.MissingProgrammerError = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun main.proto.Common.MissingProgrammerError.copy(block: `main.proto`.MissingProgrammerErrorKt.Dsl.() -> kotlin.Unit): main.proto.Common.MissingProgrammerError =
  `main.proto`.MissingProgrammerErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

