// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main/proto/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package main.proto;

@kotlin.jvm.JvmName("-initializeplatform")
public inline fun platform(block: main.proto.PlatformKt.Dsl.() -> kotlin.Unit): main.proto.Common.Platform =
  main.proto.PlatformKt.Dsl._create(main.proto.Common.Platform.newBuilder()).apply { block() }._build()
/**
 * ```
 * Platform is a structure containing all the information about a single
 * platform release.
 * ```
 *
 * Protobuf type `main.proto.Platform`
 */
public object PlatformKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: main.proto.Common.Platform.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: main.proto.Common.Platform.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): main.proto.Common.Platform = _builder.build()

    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.main.proto.PlatformMetadata metadata = 1;`
     */
    public var metadata: main.proto.Common.PlatformMetadata
      @kotlin.jvm.JvmName("getMetadata")
        get() = _builder.metadata
      @kotlin.jvm.JvmName("setMetadata")
        set(value) {
        _builder.metadata = value
      }
    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.main.proto.PlatformMetadata metadata = 1;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.main.proto.PlatformMetadata metadata = 1;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    public val PlatformKt.Dsl.metadataOrNull: main.proto.Common.PlatformMetadata?
      get() = _builder.metadataOrNull

    /**
     * ```
     * Information about a specific release of a platform.
     * ```
     *
     * `.main.proto.PlatformRelease release = 2;`
     */
    public var release: main.proto.Common.PlatformRelease
      @kotlin.jvm.JvmName("getRelease")
        get() = _builder.release
      @kotlin.jvm.JvmName("setRelease")
        set(value) {
        _builder.release = value
      }
    /**
     * ```
     * Information about a specific release of a platform.
     * ```
     *
     * `.main.proto.PlatformRelease release = 2;`
     */
    public fun clearRelease() {
      _builder.clearRelease()
    }
    /**
     * ```
     * Information about a specific release of a platform.
     * ```
     *
     * `.main.proto.PlatformRelease release = 2;`
     * @return Whether the release field is set.
     */
    public fun hasRelease(): kotlin.Boolean {
      return _builder.hasRelease()
    }

    public val PlatformKt.Dsl.releaseOrNull: main.proto.Common.PlatformRelease?
      get() = _builder.releaseOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun main.proto.Common.Platform.copy(block: `main.proto`.PlatformKt.Dsl.() -> kotlin.Unit): main.proto.Common.Platform =
  `main.proto`.PlatformKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val main.proto.Common.PlatformOrBuilder.metadataOrNull: main.proto.Common.PlatformMetadata?
  get() = if (hasMetadata()) getMetadata() else null

public val main.proto.Common.PlatformOrBuilder.releaseOrNull: main.proto.Common.PlatformRelease?
  get() = if (hasRelease()) getRelease() else null

