// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: compile.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package compiled_protocol_buffers;

@kotlin.jvm.JvmName("-initializecompileDiagnosticContext")
public inline fun compileDiagnosticContext(block: compiled_protocol_buffers.CompileDiagnosticContextKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Compile.CompileDiagnosticContext =
  compiled_protocol_buffers.CompileDiagnosticContextKt.Dsl._create(compiled_protocol_buffers.Compile.CompileDiagnosticContext.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `compiled_protocol_buffers.CompileDiagnosticContext`
 */
public object CompileDiagnosticContextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: compiled_protocol_buffers.Compile.CompileDiagnosticContext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: compiled_protocol_buffers.Compile.CompileDiagnosticContext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): compiled_protocol_buffers.Compile.CompileDiagnosticContext = _builder.build()

    /**
     * ```
     * The message describing the context reference.
     * ```
     *
     * `string message = 1;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * The message describing the context reference.
     * ```
     *
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * The file of the context reference.
     * ```
     *
     * `string file = 2;`
     */
    public var file: kotlin.String
      @kotlin.jvm.JvmName("getFile")
        get() = _builder.file
      @kotlin.jvm.JvmName("setFile")
        set(value) {
        _builder.file = value
      }
    /**
     * ```
     * The file of the context reference.
     * ```
     *
     * `string file = 2;`
     */
    public fun clearFile() {
      _builder.clearFile()
    }

    /**
     * ```
     * The line of the context reference.
     * ```
     *
     * `int64 line = 3;`
     */
    public var line: kotlin.Long
      @kotlin.jvm.JvmName("getLine")
        get() = _builder.line
      @kotlin.jvm.JvmName("setLine")
        set(value) {
        _builder.line = value
      }
    /**
     * ```
     * The line of the context reference.
     * ```
     *
     * `int64 line = 3;`
     */
    public fun clearLine() {
      _builder.clearLine()
    }

    /**
     * ```
     * The column of the context reference.
     * ```
     *
     * `int64 column = 4;`
     */
    public var column: kotlin.Long
      @kotlin.jvm.JvmName("getColumn")
        get() = _builder.column
      @kotlin.jvm.JvmName("setColumn")
        set(value) {
        _builder.column = value
      }
    /**
     * ```
     * The column of the context reference.
     * ```
     *
     * `int64 column = 4;`
     */
    public fun clearColumn() {
      _builder.clearColumn()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun compiled_protocol_buffers.Compile.CompileDiagnosticContext.copy(block: `compiled_protocol_buffers`.CompileDiagnosticContextKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Compile.CompileDiagnosticContext =
  `compiled_protocol_buffers`.CompileDiagnosticContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

