// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package compiled_protocol_buffers;

@kotlin.jvm.JvmName("-initializedownloadProgressStart")
public inline fun downloadProgressStart(block: compiled_protocol_buffers.DownloadProgressStartKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Common.DownloadProgressStart =
  compiled_protocol_buffers.DownloadProgressStartKt.Dsl._create(compiled_protocol_buffers.Common.DownloadProgressStart.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `compiled_protocol_buffers.DownloadProgressStart`
 */
public object DownloadProgressStartKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: compiled_protocol_buffers.Common.DownloadProgressStart.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: compiled_protocol_buffers.Common.DownloadProgressStart.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): compiled_protocol_buffers.Common.DownloadProgressStart = _builder.build()

    /**
     * ```
     * URL of the download.
     * ```
     *
     * `string url = 1;`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * ```
     * URL of the download.
     * ```
     *
     * `string url = 1;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * The label to display on the progress bar.
     * ```
     *
     * `string label = 2;`
     */
    public var label: kotlin.String
      @kotlin.jvm.JvmName("getLabel")
        get() = _builder.label
      @kotlin.jvm.JvmName("setLabel")
        set(value) {
        _builder.label = value
      }
    /**
     * ```
     * The label to display on the progress bar.
     * ```
     *
     * `string label = 2;`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun compiled_protocol_buffers.Common.DownloadProgressStart.copy(block: `compiled_protocol_buffers`.DownloadProgressStartKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Common.DownloadProgressStart =
  `compiled_protocol_buffers`.DownloadProgressStartKt.Dsl._create(this.toBuilder()).apply { block() }._build()

