// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lib.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package compiled_protocol_buffers;

@kotlin.jvm.JvmName("-initializelibraryListRequest")
public inline fun libraryListRequest(block: compiled_protocol_buffers.LibraryListRequestKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Lib.LibraryListRequest =
  compiled_protocol_buffers.LibraryListRequestKt.Dsl._create(compiled_protocol_buffers.Lib.LibraryListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `compiled_protocol_buffers.LibraryListRequest`
 */
public object LibraryListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: compiled_protocol_buffers.Lib.LibraryListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: compiled_protocol_buffers.Lib.LibraryListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): compiled_protocol_buffers.Lib.LibraryListRequest = _builder.build()

    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.compiled_protocol_buffers.Instance instance = 1;`
     */
    public var instance: compiled_protocol_buffers.Common.Instance
      @kotlin.jvm.JvmName("getInstance")
        get() = _builder.instance
      @kotlin.jvm.JvmName("setInstance")
        set(value) {
        _builder.instance = value
      }
    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.compiled_protocol_buffers.Instance instance = 1;`
     */
    public fun clearInstance() {
      _builder.clearInstance()
    }
    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.compiled_protocol_buffers.Instance instance = 1;`
     * @return Whether the instance field is set.
     */
    public fun hasInstance(): kotlin.Boolean {
      return _builder.hasInstance()
    }

    public val LibraryListRequestKt.Dsl.instanceOrNull: compiled_protocol_buffers.Common.Instance?
      get() = _builder.instanceOrNull

    /**
     * ```
     * Whether to include built-in libraries (from platforms and the Arduino
     * IDE) in the listing.
     * ```
     *
     * `bool all = 2;`
     */
    public var all: kotlin.Boolean
      @kotlin.jvm.JvmName("getAll")
        get() = _builder.all
      @kotlin.jvm.JvmName("setAll")
        set(value) {
        _builder.all = value
      }
    /**
     * ```
     * Whether to include built-in libraries (from platforms and the Arduino
     * IDE) in the listing.
     * ```
     *
     * `bool all = 2;`
     */
    public fun clearAll() {
      _builder.clearAll()
    }

    /**
     * ```
     * Whether to list only libraries for which there is a newer version than
     * the installed version available in the libraries index.
     * ```
     *
     * `bool updatable = 3;`
     */
    public var updatable: kotlin.Boolean
      @kotlin.jvm.JvmName("getUpdatable")
        get() = _builder.updatable
      @kotlin.jvm.JvmName("setUpdatable")
        set(value) {
        _builder.updatable = value
      }
    /**
     * ```
     * Whether to list only libraries for which there is a newer version than
     * the installed version available in the libraries index.
     * ```
     *
     * `bool updatable = 3;`
     */
    public fun clearUpdatable() {
      _builder.clearUpdatable()
    }

    /**
     * ```
     * If set filters out the libraries not matching name.
     * ```
     *
     * `string name = 4;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * If set filters out the libraries not matching name.
     * ```
     *
     * `string name = 4;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * By setting this field all duplicate libraries are filtered out leaving
     * only the libraries that will be used to compile for the specified board
     * FQBN.
     * ```
     *
     * `string fqbn = 5;`
     */
    public var fqbn: kotlin.String
      @kotlin.jvm.JvmName("getFqbn")
        get() = _builder.fqbn
      @kotlin.jvm.JvmName("setFqbn")
        set(value) {
        _builder.fqbn = value
      }
    /**
     * ```
     * By setting this field all duplicate libraries are filtered out leaving
     * only the libraries that will be used to compile for the specified board
     * FQBN.
     * ```
     *
     * `string fqbn = 5;`
     */
    public fun clearFqbn() {
      _builder.clearFqbn()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun compiled_protocol_buffers.Lib.LibraryListRequest.copy(block: `compiled_protocol_buffers`.LibraryListRequestKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Lib.LibraryListRequest =
  `compiled_protocol_buffers`.LibraryListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val compiled_protocol_buffers.Lib.LibraryListRequestOrBuilder.instanceOrNull: compiled_protocol_buffers.Common.Instance?
  get() = if (hasInstance()) getInstance() else null

