// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package compiled_protocol_buffers;

@kotlin.jvm.JvmName("-initializeplatformSummary")
public inline fun platformSummary(block: compiled_protocol_buffers.PlatformSummaryKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Common.PlatformSummary =
  compiled_protocol_buffers.PlatformSummaryKt.Dsl._create(compiled_protocol_buffers.Common.PlatformSummary.newBuilder()).apply { block() }._build()
/**
 * ```
 * PlatformSummary is a structure containing all the information about
 * a platform and all its available releases.
 * ```
 *
 * Protobuf type `compiled_protocol_buffers.PlatformSummary`
 */
public object PlatformSummaryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: compiled_protocol_buffers.Common.PlatformSummary.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: compiled_protocol_buffers.Common.PlatformSummary.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): compiled_protocol_buffers.Common.PlatformSummary = _builder.build()

    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.compiled_protocol_buffers.PlatformMetadata metadata = 1;`
     */
    public var metadata: compiled_protocol_buffers.Common.PlatformMetadata
      @kotlin.jvm.JvmName("getMetadata")
        get() = _builder.metadata
      @kotlin.jvm.JvmName("setMetadata")
        set(value) {
        _builder.metadata = value
      }
    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.compiled_protocol_buffers.PlatformMetadata metadata = 1;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.compiled_protocol_buffers.PlatformMetadata metadata = 1;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    public val PlatformSummaryKt.Dsl.metadataOrNull: compiled_protocol_buffers.Common.PlatformMetadata?
      get() = _builder.metadataOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReleasesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Maps version to the corresponding PlatformRelease.
     * ```
     *
     * `map<string, .compiled_protocol_buffers.PlatformRelease> releases = 2;`
     */
     public val releases: com.google.protobuf.kotlin.DslMap<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease, ReleasesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getReleasesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.releasesMap
      )
    /**
     * ```
     * Maps version to the corresponding PlatformRelease.
     * ```
     *
     * `map<string, .compiled_protocol_buffers.PlatformRelease> releases = 2;`
     */
    @kotlin.jvm.JvmName("putReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease, ReleasesProxy>
      .put(key: kotlin.String, value: compiled_protocol_buffers.Common.PlatformRelease) {
         _builder.putReleases(key, value)
       }
    /**
     * ```
     * Maps version to the corresponding PlatformRelease.
     * ```
     *
     * `map<string, .compiled_protocol_buffers.PlatformRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setReleases")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease, ReleasesProxy>
      .set(key: kotlin.String, value: compiled_protocol_buffers.Common.PlatformRelease) {
         put(key, value)
       }
    /**
     * ```
     * Maps version to the corresponding PlatformRelease.
     * ```
     *
     * `map<string, .compiled_protocol_buffers.PlatformRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease, ReleasesProxy>
      .remove(key: kotlin.String) {
         _builder.removeReleases(key)
       }
    /**
     * ```
     * Maps version to the corresponding PlatformRelease.
     * ```
     *
     * `map<string, .compiled_protocol_buffers.PlatformRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease, ReleasesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease>) {
         _builder.putAllReleases(map)
       }
    /**
     * ```
     * Maps version to the corresponding PlatformRelease.
     * ```
     *
     * `map<string, .compiled_protocol_buffers.PlatformRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, compiled_protocol_buffers.Common.PlatformRelease, ReleasesProxy>
      .clear() {
         _builder.clearReleases()
       }

    /**
     * ```
     * The installed version of the platform, or empty string if none installed.
     * ```
     *
     * `string installed_version = 3;`
     */
    public var installedVersion: kotlin.String
      @kotlin.jvm.JvmName("getInstalledVersion")
        get() = _builder.installedVersion
      @kotlin.jvm.JvmName("setInstalledVersion")
        set(value) {
        _builder.installedVersion = value
      }
    /**
     * ```
     * The installed version of the platform, or empty string if none installed.
     * ```
     *
     * `string installed_version = 3;`
     */
    public fun clearInstalledVersion() {
      _builder.clearInstalledVersion()
    }

    /**
     * ```
     * The latest available version of the platform that can be installable, or
     * empty if none available.
     * ```
     *
     * `string latest_version = 4;`
     */
    public var latestVersion: kotlin.String
      @kotlin.jvm.JvmName("getLatestVersion")
        get() = _builder.latestVersion
      @kotlin.jvm.JvmName("setLatestVersion")
        set(value) {
        _builder.latestVersion = value
      }
    /**
     * ```
     * The latest available version of the platform that can be installable, or
     * empty if none available.
     * ```
     *
     * `string latest_version = 4;`
     */
    public fun clearLatestVersion() {
      _builder.clearLatestVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun compiled_protocol_buffers.Common.PlatformSummary.copy(block: `compiled_protocol_buffers`.PlatformSummaryKt.Dsl.() -> kotlin.Unit): compiled_protocol_buffers.Common.PlatformSummary =
  `compiled_protocol_buffers`.PlatformSummaryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val compiled_protocol_buffers.Common.PlatformSummaryOrBuilder.metadataOrNull: compiled_protocol_buffers.Common.PlatformMetadata?
  get() = if (hasMetadata()) getMetadata() else null

