// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/compile.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public final class Compile {
  private Compile() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Compile.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_CompileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_CompileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_CompileRequest_SourceOverrideEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_CompileRequest_SourceOverrideEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_CompileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_CompileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_InstanceNeedsReinitializationError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_InstanceNeedsReinitializationError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_BuilderResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_BuilderResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_ExecutableSectionSize_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_ExecutableSectionSize_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_CompileDiagnostic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_CompileDiagnostic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_CompileDiagnosticContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_CompileDiagnosticContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_CompileDiagnosticNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_CompileDiagnosticNote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJapp/src/main/java/com/example/arduinoi" +
      "de/data/commands/proto/compile.proto\022\020pr" +
      "otocol_buffers\032Iapp/src/main/java/com/ex" +
      "ample/arduinoide/data/commands/proto/com" +
      "mon.proto\032Fapp/src/main/java/com/example" +
      "/arduinoide/data/commands/proto/lib.prot" +
      "o\"\210\006\n\016CompileRequest\022,\n\010instance\030\001 \001(\0132\032" +
      ".protocol_buffers.Instance\022\014\n\004fqbn\030\002 \001(\t" +
      "\022\023\n\013sketch_path\030\003 \001(\t\022\027\n\017show_properties" +
      "\030\004 \001(\010\022\022\n\npreprocess\030\005 \001(\010\022\034\n\020build_cach" +
      "e_path\030\006 \001(\tB\002\030\001\022\022\n\nbuild_path\030\007 \001(\t\022\030\n\020" +
      "build_properties\030\010 \003(\t\022\020\n\010warnings\030\t \001(\t" +
      "\022\017\n\007verbose\030\n \001(\010\022\r\n\005quiet\030\013 \001(\010\022\014\n\004jobs" +
      "\030\016 \001(\005\022\021\n\tlibraries\030\017 \003(\t\022\032\n\022optimize_fo" +
      "r_debug\030\020 \001(\010\022\022\n\nexport_dir\030\022 \001(\t\022\r\n\005cle" +
      "an\030\023 \001(\010\022(\n create_compilation_database_" +
      "only\030\025 \001(\010\022M\n\017source_override\030\026 \003(\01324.pr" +
      "otocol_buffers.CompileRequest.SourceOver" +
      "rideEntry\022\034\n\017export_binaries\030\027 \001(\010H\000\210\001\001\022" +
      "\017\n\007library\030\030 \003(\t\022\025\n\rkeys_keychain\030\031 \001(\t\022" +
      "\020\n\010sign_key\030\032 \001(\t\022\023\n\013encrypt_key\030\033 \001(\t\022 " +
      "\n\030skip_libraries_discovery\030\034 \001(\010\022&\n\036do_n" +
      "ot_expand_build_properties\030\035 \001(\010\022\037\n\027buil" +
      "d_cache_extra_paths\030\036 \003(\t\0325\n\023SourceOverr" +
      "ideEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "B\022\n\020_export_binaries\"\257\001\n\017CompileResponse" +
      "\022\024\n\nout_stream\030\001 \001(\014H\000\022\024\n\nerr_stream\030\002 \001" +
      "(\014H\000\0222\n\010progress\030\003 \001(\0132\036.protocol_buffer" +
      "s.TaskProgressH\000\0221\n\006result\030\004 \001(\0132\037.proto" +
      "col_buffers.BuilderResultH\000B\t\n\007message\"$" +
      "\n\"InstanceNeedsReinitializationError\"\201\003\n" +
      "\rBuilderResult\022\022\n\nbuild_path\030\001 \001(\t\0221\n\016us" +
      "ed_libraries\030\002 \003(\0132\031.protocol_buffers.Li" +
      "brary\022I\n\030executable_sections_size\030\003 \003(\0132" +
      "\'.protocol_buffers.ExecutableSectionSize" +
      "\022D\n\016board_platform\030\004 \001(\0132,.protocol_buff" +
      "ers.InstalledPlatformReference\022D\n\016build_" +
      "platform\030\005 \001(\0132,.protocol_buffers.Instal" +
      "ledPlatformReference\022\030\n\020build_properties" +
      "\030\007 \003(\t\0228\n\013diagnostics\030\010 \003(\0132#.protocol_b" +
      "uffers.CompileDiagnostic\"E\n\025ExecutableSe" +
      "ctionSize\022\014\n\004name\030\001 \001(\t\022\014\n\004size\030\002 \001(\003\022\020\n" +
      "\010max_size\030\003 \001(\003\"\327\001\n\021CompileDiagnostic\022\020\n" +
      "\010severity\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\014\n\004file" +
      "\030\003 \001(\t\022\014\n\004line\030\004 \001(\003\022\016\n\006column\030\005 \001(\003\022;\n\007" +
      "context\030\006 \003(\0132*.protocol_buffers.Compile" +
      "DiagnosticContext\0226\n\005notes\030\007 \003(\0132\'.proto" +
      "col_buffers.CompileDiagnosticNote\"W\n\030Com" +
      "pileDiagnosticContext\022\017\n\007message\030\001 \001(\t\022\014" +
      "\n\004file\030\002 \001(\t\022\014\n\004line\030\003 \001(\003\022\016\n\006column\030\004 \001" +
      "(\003\"T\n\025CompileDiagnosticNote\022\017\n\007message\030\001" +
      " \001(\t\022\014\n\004file\030\002 \001(\t\022\014\n\004line\030\003 \001(\003\022\016\n\006colu" +
      "mn\030\004 \001(\0032p\n\016CompileService\022^\n\025StreamComp" +
      "ileMessages\022 .protocol_buffers.CompileRe" +
      "quest\032!.protocol_buffers.CompileResponse" +
      "0\001B\024\n\020protocol_buffersP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol_buffers.Common.getDescriptor(),
          protocol_buffers.Lib.getDescriptor(),
        });
    internal_static_protocol_buffers_CompileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_buffers_CompileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_CompileRequest_descriptor,
        new java.lang.String[] { "Instance", "Fqbn", "SketchPath", "ShowProperties", "Preprocess", "BuildCachePath", "BuildPath", "BuildProperties", "Warnings", "Verbose", "Quiet", "Jobs", "Libraries", "OptimizeForDebug", "ExportDir", "Clean", "CreateCompilationDatabaseOnly", "SourceOverride", "ExportBinaries", "Library", "KeysKeychain", "SignKey", "EncryptKey", "SkipLibrariesDiscovery", "DoNotExpandBuildProperties", "BuildCacheExtraPaths", });
    internal_static_protocol_buffers_CompileRequest_SourceOverrideEntry_descriptor =
      internal_static_protocol_buffers_CompileRequest_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_CompileRequest_SourceOverrideEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_CompileRequest_SourceOverrideEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_buffers_CompileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_buffers_CompileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_CompileResponse_descriptor,
        new java.lang.String[] { "OutStream", "ErrStream", "Progress", "Result", "Message", });
    internal_static_protocol_buffers_InstanceNeedsReinitializationError_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_buffers_InstanceNeedsReinitializationError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_InstanceNeedsReinitializationError_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_BuilderResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_buffers_BuilderResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_BuilderResult_descriptor,
        new java.lang.String[] { "BuildPath", "UsedLibraries", "ExecutableSectionsSize", "BoardPlatform", "BuildPlatform", "BuildProperties", "Diagnostics", });
    internal_static_protocol_buffers_ExecutableSectionSize_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_buffers_ExecutableSectionSize_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_ExecutableSectionSize_descriptor,
        new java.lang.String[] { "Name", "Size", "MaxSize", });
    internal_static_protocol_buffers_CompileDiagnostic_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protocol_buffers_CompileDiagnostic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_CompileDiagnostic_descriptor,
        new java.lang.String[] { "Severity", "Message", "File", "Line", "Column", "Context", "Notes", });
    internal_static_protocol_buffers_CompileDiagnosticContext_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protocol_buffers_CompileDiagnosticContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_CompileDiagnosticContext_descriptor,
        new java.lang.String[] { "Message", "File", "Line", "Column", });
    internal_static_protocol_buffers_CompileDiagnosticNote_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protocol_buffers_CompileDiagnosticNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_CompileDiagnosticNote_descriptor,
        new java.lang.String[] { "Message", "File", "Line", "Column", });
    descriptor.resolveAllFeaturesImmutable();
    protocol_buffers.Common.getDescriptor();
    protocol_buffers.Lib.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
