// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/compile.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

/**
 * Protobuf type {@code protocol_buffers.CompileResponse}
 */
@com.google.protobuf.Generated
public final class CompileResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol_buffers.CompileResponse)
    CompileResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      CompileResponse.class.getName());
  }
  // Use CompileResponse.newBuilder() to construct.
  private CompileResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CompileResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol_buffers.Compile.internal_static_protocol_buffers_CompileResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol_buffers.Compile.internal_static_protocol_buffers_CompileResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol_buffers.CompileResponse.class, protocol_buffers.CompileResponse.Builder.class);
  }

  private int messageCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    OUT_STREAM(1),
    ERR_STREAM(2),
    PROGRESS(3),
    RESULT(4),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return OUT_STREAM;
        case 2: return ERR_STREAM;
        case 3: return PROGRESS;
        case 4: return RESULT;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int OUT_STREAM_FIELD_NUMBER = 1;
  /**
   * <pre>
   * The output of the compilation process (stream).
   * </pre>
   *
   * <code>bytes out_stream = 1;</code>
   * @return Whether the outStream field is set.
   */
  @java.lang.Override
  public boolean hasOutStream() {
    return messageCase_ == 1;
  }
  /**
   * <pre>
   * The output of the compilation process (stream).
   * </pre>
   *
   * <code>bytes out_stream = 1;</code>
   * @return The outStream.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getOutStream() {
    if (messageCase_ == 1) {
      return (com.google.protobuf.ByteString) message_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int ERR_STREAM_FIELD_NUMBER = 2;
  /**
   * <pre>
   * The error output of the compilation process (stream).
   * </pre>
   *
   * <code>bytes err_stream = 2;</code>
   * @return Whether the errStream field is set.
   */
  @java.lang.Override
  public boolean hasErrStream() {
    return messageCase_ == 2;
  }
  /**
   * <pre>
   * The error output of the compilation process (stream).
   * </pre>
   *
   * <code>bytes err_stream = 2;</code>
   * @return The errStream.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getErrStream() {
    if (messageCase_ == 2) {
      return (com.google.protobuf.ByteString) message_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int PROGRESS_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Completions reports of the compilation process (stream).
   * </pre>
   *
   * <code>.protocol_buffers.TaskProgress progress = 3;</code>
   * @return Whether the progress field is set.
   */
  @java.lang.Override
  public boolean hasProgress() {
    return messageCase_ == 3;
  }
  /**
   * <pre>
   * Completions reports of the compilation process (stream).
   * </pre>
   *
   * <code>.protocol_buffers.TaskProgress progress = 3;</code>
   * @return The progress.
   */
  @java.lang.Override
  public protocol_buffers.TaskProgress getProgress() {
    if (messageCase_ == 3) {
       return (protocol_buffers.TaskProgress) message_;
    }
    return protocol_buffers.TaskProgress.getDefaultInstance();
  }
  /**
   * <pre>
   * Completions reports of the compilation process (stream).
   * </pre>
   *
   * <code>.protocol_buffers.TaskProgress progress = 3;</code>
   */
  @java.lang.Override
  public protocol_buffers.TaskProgressOrBuilder getProgressOrBuilder() {
    if (messageCase_ == 3) {
       return (protocol_buffers.TaskProgress) message_;
    }
    return protocol_buffers.TaskProgress.getDefaultInstance();
  }

  public static final int RESULT_FIELD_NUMBER = 4;
  /**
   * <pre>
   * The compilation result.
   * </pre>
   *
   * <code>.protocol_buffers.BuilderResult result = 4;</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return messageCase_ == 4;
  }
  /**
   * <pre>
   * The compilation result.
   * </pre>
   *
   * <code>.protocol_buffers.BuilderResult result = 4;</code>
   * @return The result.
   */
  @java.lang.Override
  public protocol_buffers.BuilderResult getResult() {
    if (messageCase_ == 4) {
       return (protocol_buffers.BuilderResult) message_;
    }
    return protocol_buffers.BuilderResult.getDefaultInstance();
  }
  /**
   * <pre>
   * The compilation result.
   * </pre>
   *
   * <code>.protocol_buffers.BuilderResult result = 4;</code>
   */
  @java.lang.Override
  public protocol_buffers.BuilderResultOrBuilder getResultOrBuilder() {
    if (messageCase_ == 4) {
       return (protocol_buffers.BuilderResult) message_;
    }
    return protocol_buffers.BuilderResult.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeBytes(
          1, (com.google.protobuf.ByteString) message_);
    }
    if (messageCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) message_);
    }
    if (messageCase_ == 3) {
      output.writeMessage(3, (protocol_buffers.TaskProgress) message_);
    }
    if (messageCase_ == 4) {
      output.writeMessage(4, (protocol_buffers.BuilderResult) message_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            1, (com.google.protobuf.ByteString) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) message_);
    }
    if (messageCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (protocol_buffers.TaskProgress) message_);
    }
    if (messageCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (protocol_buffers.BuilderResult) message_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol_buffers.CompileResponse)) {
      return super.equals(obj);
    }
    protocol_buffers.CompileResponse other = (protocol_buffers.CompileResponse) obj;

    if (!getMessageCase().equals(other.getMessageCase())) return false;
    switch (messageCase_) {
      case 1:
        if (!getOutStream()
            .equals(other.getOutStream())) return false;
        break;
      case 2:
        if (!getErrStream()
            .equals(other.getErrStream())) return false;
        break;
      case 3:
        if (!getProgress()
            .equals(other.getProgress())) return false;
        break;
      case 4:
        if (!getResult()
            .equals(other.getResult())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + OUT_STREAM_FIELD_NUMBER;
        hash = (53 * hash) + getOutStream().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ERR_STREAM_FIELD_NUMBER;
        hash = (53 * hash) + getErrStream().hashCode();
        break;
      case 3:
        hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
        hash = (53 * hash) + getProgress().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol_buffers.CompileResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.CompileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.CompileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static protocol_buffers.CompileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static protocol_buffers.CompileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.CompileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol_buffers.CompileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol_buffers.CompileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol_buffers.CompileResponse)
      protocol_buffers.CompileResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_buffers.Compile.internal_static_protocol_buffers_CompileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_buffers.Compile.internal_static_protocol_buffers_CompileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_buffers.CompileResponse.class, protocol_buffers.CompileResponse.Builder.class);
    }

    // Construct using protocol_buffers.CompileResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (progressBuilder_ != null) {
        progressBuilder_.clear();
      }
      if (resultBuilder_ != null) {
        resultBuilder_.clear();
      }
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol_buffers.Compile.internal_static_protocol_buffers_CompileResponse_descriptor;
    }

    @java.lang.Override
    public protocol_buffers.CompileResponse getDefaultInstanceForType() {
      return protocol_buffers.CompileResponse.getDefaultInstance();
    }

    @java.lang.Override
    public protocol_buffers.CompileResponse build() {
      protocol_buffers.CompileResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol_buffers.CompileResponse buildPartial() {
      protocol_buffers.CompileResponse result = new protocol_buffers.CompileResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(protocol_buffers.CompileResponse result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(protocol_buffers.CompileResponse result) {
      result.messageCase_ = messageCase_;
      result.message_ = this.message_;
      if (messageCase_ == 3 &&
          progressBuilder_ != null) {
        result.message_ = progressBuilder_.build();
      }
      if (messageCase_ == 4 &&
          resultBuilder_ != null) {
        result.message_ = resultBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol_buffers.CompileResponse) {
        return mergeFrom((protocol_buffers.CompileResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol_buffers.CompileResponse other) {
      if (other == protocol_buffers.CompileResponse.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case OUT_STREAM: {
          setOutStream(other.getOutStream());
          break;
        }
        case ERR_STREAM: {
          setErrStream(other.getErrStream());
          break;
        }
        case PROGRESS: {
          mergeProgress(other.getProgress());
          break;
        }
        case RESULT: {
          mergeResult(other.getResult());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              message_ = input.readBytes();
              messageCase_ = 1;
              break;
            } // case 10
            case 18: {
              message_ = input.readBytes();
              messageCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetProgressFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * The output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes out_stream = 1;</code>
     * @return Whether the outStream field is set.
     */
    public boolean hasOutStream() {
      return messageCase_ == 1;
    }
    /**
     * <pre>
     * The output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes out_stream = 1;</code>
     * @return The outStream.
     */
    public com.google.protobuf.ByteString getOutStream() {
      if (messageCase_ == 1) {
        return (com.google.protobuf.ByteString) message_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * The output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes out_stream = 1;</code>
     * @param value The outStream to set.
     * @return This builder for chaining.
     */
    public Builder setOutStream(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      messageCase_ = 1;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes out_stream = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutStream() {
      if (messageCase_ == 1) {
        messageCase_ = 0;
        message_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * The error output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes err_stream = 2;</code>
     * @return Whether the errStream field is set.
     */
    public boolean hasErrStream() {
      return messageCase_ == 2;
    }
    /**
     * <pre>
     * The error output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes err_stream = 2;</code>
     * @return The errStream.
     */
    public com.google.protobuf.ByteString getErrStream() {
      if (messageCase_ == 2) {
        return (com.google.protobuf.ByteString) message_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * The error output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes err_stream = 2;</code>
     * @param value The errStream to set.
     * @return This builder for chaining.
     */
    public Builder setErrStream(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      messageCase_ = 2;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The error output of the compilation process (stream).
     * </pre>
     *
     * <code>bytes err_stream = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrStream() {
      if (messageCase_ == 2) {
        messageCase_ = 0;
        message_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        protocol_buffers.TaskProgress, protocol_buffers.TaskProgress.Builder, protocol_buffers.TaskProgressOrBuilder> progressBuilder_;
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     * @return Whether the progress field is set.
     */
    @java.lang.Override
    public boolean hasProgress() {
      return messageCase_ == 3;
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     * @return The progress.
     */
    @java.lang.Override
    public protocol_buffers.TaskProgress getProgress() {
      if (progressBuilder_ == null) {
        if (messageCase_ == 3) {
          return (protocol_buffers.TaskProgress) message_;
        }
        return protocol_buffers.TaskProgress.getDefaultInstance();
      } else {
        if (messageCase_ == 3) {
          return progressBuilder_.getMessage();
        }
        return protocol_buffers.TaskProgress.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    public Builder setProgress(protocol_buffers.TaskProgress value) {
      if (progressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        progressBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    public Builder setProgress(
        protocol_buffers.TaskProgress.Builder builderForValue) {
      if (progressBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        progressBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    public Builder mergeProgress(protocol_buffers.TaskProgress value) {
      if (progressBuilder_ == null) {
        if (messageCase_ == 3 &&
            message_ != protocol_buffers.TaskProgress.getDefaultInstance()) {
          message_ = protocol_buffers.TaskProgress.newBuilder((protocol_buffers.TaskProgress) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 3) {
          progressBuilder_.mergeFrom(value);
        } else {
          progressBuilder_.setMessage(value);
        }
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    public Builder clearProgress() {
      if (progressBuilder_ == null) {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
        }
        progressBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    public protocol_buffers.TaskProgress.Builder getProgressBuilder() {
      return internalGetProgressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    @java.lang.Override
    public protocol_buffers.TaskProgressOrBuilder getProgressOrBuilder() {
      if ((messageCase_ == 3) && (progressBuilder_ != null)) {
        return progressBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 3) {
          return (protocol_buffers.TaskProgress) message_;
        }
        return protocol_buffers.TaskProgress.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Completions reports of the compilation process (stream).
     * </pre>
     *
     * <code>.protocol_buffers.TaskProgress progress = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        protocol_buffers.TaskProgress, protocol_buffers.TaskProgress.Builder, protocol_buffers.TaskProgressOrBuilder> 
        internalGetProgressFieldBuilder() {
      if (progressBuilder_ == null) {
        if (!(messageCase_ == 3)) {
          message_ = protocol_buffers.TaskProgress.getDefaultInstance();
        }
        progressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            protocol_buffers.TaskProgress, protocol_buffers.TaskProgress.Builder, protocol_buffers.TaskProgressOrBuilder>(
                (protocol_buffers.TaskProgress) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 3;
      onChanged();
      return progressBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        protocol_buffers.BuilderResult, protocol_buffers.BuilderResult.Builder, protocol_buffers.BuilderResultOrBuilder> resultBuilder_;
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override
    public boolean hasResult() {
      return messageCase_ == 4;
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     * @return The result.
     */
    @java.lang.Override
    public protocol_buffers.BuilderResult getResult() {
      if (resultBuilder_ == null) {
        if (messageCase_ == 4) {
          return (protocol_buffers.BuilderResult) message_;
        }
        return protocol_buffers.BuilderResult.getDefaultInstance();
      } else {
        if (messageCase_ == 4) {
          return resultBuilder_.getMessage();
        }
        return protocol_buffers.BuilderResult.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    public Builder setResult(protocol_buffers.BuilderResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    public Builder setResult(
        protocol_buffers.BuilderResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    public Builder mergeResult(protocol_buffers.BuilderResult value) {
      if (resultBuilder_ == null) {
        if (messageCase_ == 4 &&
            message_ != protocol_buffers.BuilderResult.getDefaultInstance()) {
          message_ = protocol_buffers.BuilderResult.newBuilder((protocol_buffers.BuilderResult) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 4) {
          resultBuilder_.mergeFrom(value);
        } else {
          resultBuilder_.setMessage(value);
        }
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
        }
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    public protocol_buffers.BuilderResult.Builder getResultBuilder() {
      return internalGetResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    @java.lang.Override
    public protocol_buffers.BuilderResultOrBuilder getResultOrBuilder() {
      if ((messageCase_ == 4) && (resultBuilder_ != null)) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 4) {
          return (protocol_buffers.BuilderResult) message_;
        }
        return protocol_buffers.BuilderResult.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * The compilation result.
     * </pre>
     *
     * <code>.protocol_buffers.BuilderResult result = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        protocol_buffers.BuilderResult, protocol_buffers.BuilderResult.Builder, protocol_buffers.BuilderResultOrBuilder> 
        internalGetResultFieldBuilder() {
      if (resultBuilder_ == null) {
        if (!(messageCase_ == 4)) {
          message_ = protocol_buffers.BuilderResult.getDefaultInstance();
        }
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            protocol_buffers.BuilderResult, protocol_buffers.BuilderResult.Builder, protocol_buffers.BuilderResultOrBuilder>(
                (protocol_buffers.BuilderResult) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 4;
      onChanged();
      return resultBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:protocol_buffers.CompileResponse)
  }

  // @@protoc_insertion_point(class_scope:protocol_buffers.CompileResponse)
  private static final protocol_buffers.CompileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol_buffers.CompileResponse();
  }

  public static protocol_buffers.CompileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompileResponse>
      PARSER = new com.google.protobuf.AbstractParser<CompileResponse>() {
    @java.lang.Override
    public CompileResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompileResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompileResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol_buffers.CompileResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

