// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/compile.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public interface ExecutableSectionSizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol_buffers.ExecutableSectionSize)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the section.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the section.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The used size of the section in bytes.
   * </pre>
   *
   * <code>int64 size = 2;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <pre>
   * The maximum size of the section in bytes.
   * </pre>
   *
   * <code>int64 max_size = 3;</code>
   * @return The maxSize.
   */
  long getMaxSize();
}
