// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/lib.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol_buffers;

@kotlin.jvm.JvmName("-initializegitLibraryInstallResponse")
public inline fun gitLibraryInstallResponse(block: protocol_buffers.GitLibraryInstallResponseKt.Dsl.() -> kotlin.Unit): protocol_buffers.GitLibraryInstallResponse =
  protocol_buffers.GitLibraryInstallResponseKt.Dsl._create(protocol_buffers.GitLibraryInstallResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol_buffers.GitLibraryInstallResponse`
 */
public object GitLibraryInstallResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol_buffers.GitLibraryInstallResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: protocol_buffers.GitLibraryInstallResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): protocol_buffers.GitLibraryInstallResponse = _builder.build()

    /**
     * ```
     * Description of the current stage of the installation.
     * ```
     *
     * `.protocol_buffers.TaskProgress task_progress = 1;`
     */
    public var taskProgress: protocol_buffers.TaskProgress
      @kotlin.jvm.JvmName("getTaskProgress")
        get() = _builder.taskProgress
      @kotlin.jvm.JvmName("setTaskProgress")
        set(value) {
        _builder.taskProgress = value
      }
    /**
     * ```
     * Description of the current stage of the installation.
     * ```
     *
     * `.protocol_buffers.TaskProgress task_progress = 1;`
     */
    public fun clearTaskProgress() {
      _builder.clearTaskProgress()
    }
    /**
     * ```
     * Description of the current stage of the installation.
     * ```
     *
     * `.protocol_buffers.TaskProgress task_progress = 1;`
     * @return Whether the taskProgress field is set.
     */
    public fun hasTaskProgress(): kotlin.Boolean {
      return _builder.hasTaskProgress()
    }

    /**
     * ```
     * Installation result.
     * ```
     *
     * `.protocol_buffers.GitLibraryInstallResponse.Result result = 2;`
     */
    public var result: protocol_buffers.GitLibraryInstallResponse.Result
      @kotlin.jvm.JvmName("getResult")
        get() = _builder.result
      @kotlin.jvm.JvmName("setResult")
        set(value) {
        _builder.result = value
      }
    /**
     * ```
     * Installation result.
     * ```
     *
     * `.protocol_buffers.GitLibraryInstallResponse.Result result = 2;`
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * ```
     * Installation result.
     * ```
     *
     * `.protocol_buffers.GitLibraryInstallResponse.Result result = 2;`
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }
    public val messageCase: protocol_buffers.GitLibraryInstallResponse.MessageCase
    @kotlin.jvm.JvmName("getMessageCase")
      get() = _builder.getMessageCase()

    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
  @kotlin.jvm.JvmName("-initializeresult")
  public inline fun result(block: protocol_buffers.GitLibraryInstallResponseKt.ResultKt.Dsl.() -> kotlin.Unit): protocol_buffers.GitLibraryInstallResponse.Result =
    protocol_buffers.GitLibraryInstallResponseKt.ResultKt.Dsl._create(protocol_buffers.GitLibraryInstallResponse.Result.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Empty message, reserved for future expansion.
   * ```
   *
   * Protobuf type `protocol_buffers.GitLibraryInstallResponse.Result`
   */
  public object ResultKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: protocol_buffers.GitLibraryInstallResponse.Result.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: protocol_buffers.GitLibraryInstallResponse.Result.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): protocol_buffers.GitLibraryInstallResponse.Result = _builder.build()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol_buffers.GitLibraryInstallResponse.copy(block: `protocol_buffers`.GitLibraryInstallResponseKt.Dsl.() -> kotlin.Unit): protocol_buffers.GitLibraryInstallResponse =
  `protocol_buffers`.GitLibraryInstallResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun protocol_buffers.GitLibraryInstallResponse.Result.copy(block: `protocol_buffers`.GitLibraryInstallResponseKt.ResultKt.Dsl.() -> kotlin.Unit): protocol_buffers.GitLibraryInstallResponse.Result =
  `protocol_buffers`.GitLibraryInstallResponseKt.ResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol_buffers.GitLibraryInstallResponseOrBuilder.taskProgressOrNull: protocol_buffers.TaskProgress?
  get() = if (hasTaskProgress()) getTaskProgress() else null

public val protocol_buffers.GitLibraryInstallResponseOrBuilder.resultOrNull: protocol_buffers.GitLibraryInstallResponse.Result?
  get() = if (hasResult()) getResult() else null

