// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/common.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public interface InstalledPlatformReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol_buffers.InstalledPlatformReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Platform ID (e.g., `arduino:avr`).
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Platform ID (e.g., `arduino:avr`).
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Version of the platform.
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * Version of the platform.
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * Installation directory of the platform.
   * </pre>
   *
   * <code>string install_dir = 3;</code>
   * @return The installDir.
   */
  java.lang.String getInstallDir();
  /**
   * <pre>
   * Installation directory of the platform.
   * </pre>
   *
   * <code>string install_dir = 3;</code>
   * @return The bytes for installDir.
   */
  com.google.protobuf.ByteString
      getInstallDirBytes();

  /**
   * <pre>
   * 3rd party platform URL.
   * </pre>
   *
   * <code>string package_url = 4;</code>
   * @return The packageUrl.
   */
  java.lang.String getPackageUrl();
  /**
   * <pre>
   * 3rd party platform URL.
   * </pre>
   *
   * <code>string package_url = 4;</code>
   * @return The bytes for packageUrl.
   */
  com.google.protobuf.ByteString
      getPackageUrlBytes();
}
