// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/lib.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

/**
 * Protobuf type {@code protocol_buffers.LibraryDependencyStatus}
 */
@com.google.protobuf.Generated
public final class LibraryDependencyStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol_buffers.LibraryDependencyStatus)
    LibraryDependencyStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      LibraryDependencyStatus.class.getName());
  }
  // Use LibraryDependencyStatus.newBuilder() to construct.
  private LibraryDependencyStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LibraryDependencyStatus() {
    name_ = "";
    versionRequired_ = "";
    versionInstalled_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol_buffers.Lib.internal_static_protocol_buffers_LibraryDependencyStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol_buffers.Lib.internal_static_protocol_buffers_LibraryDependencyStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol_buffers.LibraryDependencyStatus.class, protocol_buffers.LibraryDependencyStatus.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The name of the library dependency.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the library dependency.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_REQUIRED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object versionRequired_ = "";
  /**
   * <pre>
   * The required version of the library dependency.
   * </pre>
   *
   * <code>string version_required = 2;</code>
   * @return The versionRequired.
   */
  @java.lang.Override
  public java.lang.String getVersionRequired() {
    java.lang.Object ref = versionRequired_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      versionRequired_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The required version of the library dependency.
   * </pre>
   *
   * <code>string version_required = 2;</code>
   * @return The bytes for versionRequired.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionRequiredBytes() {
    java.lang.Object ref = versionRequired_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      versionRequired_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_INSTALLED_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object versionInstalled_ = "";
  /**
   * <pre>
   * Version of the library dependency currently installed.
   * </pre>
   *
   * <code>string version_installed = 3;</code>
   * @return The versionInstalled.
   */
  @java.lang.Override
  public java.lang.String getVersionInstalled() {
    java.lang.Object ref = versionInstalled_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      versionInstalled_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of the library dependency currently installed.
   * </pre>
   *
   * <code>string version_installed = 3;</code>
   * @return The bytes for versionInstalled.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionInstalledBytes() {
    java.lang.Object ref = versionInstalled_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      versionInstalled_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(versionRequired_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, versionRequired_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(versionInstalled_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, versionInstalled_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(versionRequired_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, versionRequired_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(versionInstalled_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, versionInstalled_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol_buffers.LibraryDependencyStatus)) {
      return super.equals(obj);
    }
    protocol_buffers.LibraryDependencyStatus other = (protocol_buffers.LibraryDependencyStatus) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getVersionRequired()
        .equals(other.getVersionRequired())) return false;
    if (!getVersionInstalled()
        .equals(other.getVersionInstalled())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VERSION_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + getVersionRequired().hashCode();
    hash = (37 * hash) + VERSION_INSTALLED_FIELD_NUMBER;
    hash = (53 * hash) + getVersionInstalled().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static protocol_buffers.LibraryDependencyStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static protocol_buffers.LibraryDependencyStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.LibraryDependencyStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol_buffers.LibraryDependencyStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol_buffers.LibraryDependencyStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol_buffers.LibraryDependencyStatus)
      protocol_buffers.LibraryDependencyStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_buffers.Lib.internal_static_protocol_buffers_LibraryDependencyStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_buffers.Lib.internal_static_protocol_buffers_LibraryDependencyStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_buffers.LibraryDependencyStatus.class, protocol_buffers.LibraryDependencyStatus.Builder.class);
    }

    // Construct using protocol_buffers.LibraryDependencyStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      versionRequired_ = "";
      versionInstalled_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol_buffers.Lib.internal_static_protocol_buffers_LibraryDependencyStatus_descriptor;
    }

    @java.lang.Override
    public protocol_buffers.LibraryDependencyStatus getDefaultInstanceForType() {
      return protocol_buffers.LibraryDependencyStatus.getDefaultInstance();
    }

    @java.lang.Override
    public protocol_buffers.LibraryDependencyStatus build() {
      protocol_buffers.LibraryDependencyStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol_buffers.LibraryDependencyStatus buildPartial() {
      protocol_buffers.LibraryDependencyStatus result = new protocol_buffers.LibraryDependencyStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protocol_buffers.LibraryDependencyStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.versionRequired_ = versionRequired_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.versionInstalled_ = versionInstalled_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol_buffers.LibraryDependencyStatus) {
        return mergeFrom((protocol_buffers.LibraryDependencyStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol_buffers.LibraryDependencyStatus other) {
      if (other == protocol_buffers.LibraryDependencyStatus.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getVersionRequired().isEmpty()) {
        versionRequired_ = other.versionRequired_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getVersionInstalled().isEmpty()) {
        versionInstalled_ = other.versionInstalled_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              versionRequired_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              versionInstalled_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The name of the library dependency.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the library dependency.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the library dependency.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the library dependency.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the library dependency.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object versionRequired_ = "";
    /**
     * <pre>
     * The required version of the library dependency.
     * </pre>
     *
     * <code>string version_required = 2;</code>
     * @return The versionRequired.
     */
    public java.lang.String getVersionRequired() {
      java.lang.Object ref = versionRequired_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        versionRequired_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The required version of the library dependency.
     * </pre>
     *
     * <code>string version_required = 2;</code>
     * @return The bytes for versionRequired.
     */
    public com.google.protobuf.ByteString
        getVersionRequiredBytes() {
      java.lang.Object ref = versionRequired_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionRequired_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The required version of the library dependency.
     * </pre>
     *
     * <code>string version_required = 2;</code>
     * @param value The versionRequired to set.
     * @return This builder for chaining.
     */
    public Builder setVersionRequired(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      versionRequired_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The required version of the library dependency.
     * </pre>
     *
     * <code>string version_required = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersionRequired() {
      versionRequired_ = getDefaultInstance().getVersionRequired();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The required version of the library dependency.
     * </pre>
     *
     * <code>string version_required = 2;</code>
     * @param value The bytes for versionRequired to set.
     * @return This builder for chaining.
     */
    public Builder setVersionRequiredBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      versionRequired_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object versionInstalled_ = "";
    /**
     * <pre>
     * Version of the library dependency currently installed.
     * </pre>
     *
     * <code>string version_installed = 3;</code>
     * @return The versionInstalled.
     */
    public java.lang.String getVersionInstalled() {
      java.lang.Object ref = versionInstalled_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        versionInstalled_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of the library dependency currently installed.
     * </pre>
     *
     * <code>string version_installed = 3;</code>
     * @return The bytes for versionInstalled.
     */
    public com.google.protobuf.ByteString
        getVersionInstalledBytes() {
      java.lang.Object ref = versionInstalled_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionInstalled_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of the library dependency currently installed.
     * </pre>
     *
     * <code>string version_installed = 3;</code>
     * @param value The versionInstalled to set.
     * @return This builder for chaining.
     */
    public Builder setVersionInstalled(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      versionInstalled_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the library dependency currently installed.
     * </pre>
     *
     * <code>string version_installed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersionInstalled() {
      versionInstalled_ = getDefaultInstance().getVersionInstalled();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the library dependency currently installed.
     * </pre>
     *
     * <code>string version_installed = 3;</code>
     * @param value The bytes for versionInstalled to set.
     * @return This builder for chaining.
     */
    public Builder setVersionInstalledBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      versionInstalled_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:protocol_buffers.LibraryDependencyStatus)
  }

  // @@protoc_insertion_point(class_scope:protocol_buffers.LibraryDependencyStatus)
  private static final protocol_buffers.LibraryDependencyStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol_buffers.LibraryDependencyStatus();
  }

  public static protocol_buffers.LibraryDependencyStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LibraryDependencyStatus>
      PARSER = new com.google.protobuf.AbstractParser<LibraryDependencyStatus>() {
    @java.lang.Override
    public LibraryDependencyStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LibraryDependencyStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibraryDependencyStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol_buffers.LibraryDependencyStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

