// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/lib.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

/**
 * Protobuf type {@code protocol_buffers.LibrarySearchResponse}
 */
@com.google.protobuf.Generated
public final class LibrarySearchResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol_buffers.LibrarySearchResponse)
    LibrarySearchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      LibrarySearchResponse.class.getName());
  }
  // Use LibrarySearchResponse.newBuilder() to construct.
  private LibrarySearchResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LibrarySearchResponse() {
    libraries_ = java.util.Collections.emptyList();
    status_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol_buffers.Lib.internal_static_protocol_buffers_LibrarySearchResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol_buffers.Lib.internal_static_protocol_buffers_LibrarySearchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol_buffers.LibrarySearchResponse.class, protocol_buffers.LibrarySearchResponse.Builder.class);
  }

  public static final int LIBRARIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<protocol_buffers.SearchedLibrary> libraries_;
  /**
   * <pre>
   * The results of the search.
   * </pre>
   *
   * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protocol_buffers.SearchedLibrary> getLibrariesList() {
    return libraries_;
  }
  /**
   * <pre>
   * The results of the search.
   * </pre>
   *
   * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protocol_buffers.SearchedLibraryOrBuilder> 
      getLibrariesOrBuilderList() {
    return libraries_;
  }
  /**
   * <pre>
   * The results of the search.
   * </pre>
   *
   * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
   */
  @java.lang.Override
  public int getLibrariesCount() {
    return libraries_.size();
  }
  /**
   * <pre>
   * The results of the search.
   * </pre>
   *
   * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
   */
  @java.lang.Override
  public protocol_buffers.SearchedLibrary getLibraries(int index) {
    return libraries_.get(index);
  }
  /**
   * <pre>
   * The results of the search.
   * </pre>
   *
   * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
   */
  @java.lang.Override
  public protocol_buffers.SearchedLibraryOrBuilder getLibrariesOrBuilder(
      int index) {
    return libraries_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <pre>
   * Whether the search yielded results.
   * </pre>
   *
   * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * Whether the search yielded results.
   * </pre>
   *
   * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
   * @return The status.
   */
  @java.lang.Override public protocol_buffers.LibrarySearchStatus getStatus() {
    protocol_buffers.LibrarySearchStatus result = protocol_buffers.LibrarySearchStatus.forNumber(status_);
    return result == null ? protocol_buffers.LibrarySearchStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < libraries_.size(); i++) {
      output.writeMessage(1, libraries_.get(i));
    }
    if (status_ != protocol_buffers.LibrarySearchStatus.LIBRARY_SEARCH_STATUS_FAILED.getNumber()) {
      output.writeEnum(2, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < libraries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, libraries_.get(i));
    }
    if (status_ != protocol_buffers.LibrarySearchStatus.LIBRARY_SEARCH_STATUS_FAILED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol_buffers.LibrarySearchResponse)) {
      return super.equals(obj);
    }
    protocol_buffers.LibrarySearchResponse other = (protocol_buffers.LibrarySearchResponse) obj;

    if (!getLibrariesList()
        .equals(other.getLibrariesList())) return false;
    if (status_ != other.status_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLibrariesCount() > 0) {
      hash = (37 * hash) + LIBRARIES_FIELD_NUMBER;
      hash = (53 * hash) + getLibrariesList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol_buffers.LibrarySearchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static protocol_buffers.LibrarySearchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static protocol_buffers.LibrarySearchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.LibrarySearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol_buffers.LibrarySearchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol_buffers.LibrarySearchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol_buffers.LibrarySearchResponse)
      protocol_buffers.LibrarySearchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_buffers.Lib.internal_static_protocol_buffers_LibrarySearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_buffers.Lib.internal_static_protocol_buffers_LibrarySearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_buffers.LibrarySearchResponse.class, protocol_buffers.LibrarySearchResponse.Builder.class);
    }

    // Construct using protocol_buffers.LibrarySearchResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (librariesBuilder_ == null) {
        libraries_ = java.util.Collections.emptyList();
      } else {
        libraries_ = null;
        librariesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol_buffers.Lib.internal_static_protocol_buffers_LibrarySearchResponse_descriptor;
    }

    @java.lang.Override
    public protocol_buffers.LibrarySearchResponse getDefaultInstanceForType() {
      return protocol_buffers.LibrarySearchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public protocol_buffers.LibrarySearchResponse build() {
      protocol_buffers.LibrarySearchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol_buffers.LibrarySearchResponse buildPartial() {
      protocol_buffers.LibrarySearchResponse result = new protocol_buffers.LibrarySearchResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(protocol_buffers.LibrarySearchResponse result) {
      if (librariesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          libraries_ = java.util.Collections.unmodifiableList(libraries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.libraries_ = libraries_;
      } else {
        result.libraries_ = librariesBuilder_.build();
      }
    }

    private void buildPartial0(protocol_buffers.LibrarySearchResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol_buffers.LibrarySearchResponse) {
        return mergeFrom((protocol_buffers.LibrarySearchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol_buffers.LibrarySearchResponse other) {
      if (other == protocol_buffers.LibrarySearchResponse.getDefaultInstance()) return this;
      if (librariesBuilder_ == null) {
        if (!other.libraries_.isEmpty()) {
          if (libraries_.isEmpty()) {
            libraries_ = other.libraries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLibrariesIsMutable();
            libraries_.addAll(other.libraries_);
          }
          onChanged();
        }
      } else {
        if (!other.libraries_.isEmpty()) {
          if (librariesBuilder_.isEmpty()) {
            librariesBuilder_.dispose();
            librariesBuilder_ = null;
            libraries_ = other.libraries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            librariesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetLibrariesFieldBuilder() : null;
          } else {
            librariesBuilder_.addAllMessages(other.libraries_);
          }
        }
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protocol_buffers.SearchedLibrary m =
                  input.readMessage(
                      protocol_buffers.SearchedLibrary.parser(),
                      extensionRegistry);
              if (librariesBuilder_ == null) {
                ensureLibrariesIsMutable();
                libraries_.add(m);
              } else {
                librariesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<protocol_buffers.SearchedLibrary> libraries_ =
      java.util.Collections.emptyList();
    private void ensureLibrariesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        libraries_ = new java.util.ArrayList<protocol_buffers.SearchedLibrary>(libraries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        protocol_buffers.SearchedLibrary, protocol_buffers.SearchedLibrary.Builder, protocol_buffers.SearchedLibraryOrBuilder> librariesBuilder_;

    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public java.util.List<protocol_buffers.SearchedLibrary> getLibrariesList() {
      if (librariesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(libraries_);
      } else {
        return librariesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public int getLibrariesCount() {
      if (librariesBuilder_ == null) {
        return libraries_.size();
      } else {
        return librariesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public protocol_buffers.SearchedLibrary getLibraries(int index) {
      if (librariesBuilder_ == null) {
        return libraries_.get(index);
      } else {
        return librariesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder setLibraries(
        int index, protocol_buffers.SearchedLibrary value) {
      if (librariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLibrariesIsMutable();
        libraries_.set(index, value);
        onChanged();
      } else {
        librariesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder setLibraries(
        int index, protocol_buffers.SearchedLibrary.Builder builderForValue) {
      if (librariesBuilder_ == null) {
        ensureLibrariesIsMutable();
        libraries_.set(index, builderForValue.build());
        onChanged();
      } else {
        librariesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder addLibraries(protocol_buffers.SearchedLibrary value) {
      if (librariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLibrariesIsMutable();
        libraries_.add(value);
        onChanged();
      } else {
        librariesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder addLibraries(
        int index, protocol_buffers.SearchedLibrary value) {
      if (librariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLibrariesIsMutable();
        libraries_.add(index, value);
        onChanged();
      } else {
        librariesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder addLibraries(
        protocol_buffers.SearchedLibrary.Builder builderForValue) {
      if (librariesBuilder_ == null) {
        ensureLibrariesIsMutable();
        libraries_.add(builderForValue.build());
        onChanged();
      } else {
        librariesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder addLibraries(
        int index, protocol_buffers.SearchedLibrary.Builder builderForValue) {
      if (librariesBuilder_ == null) {
        ensureLibrariesIsMutable();
        libraries_.add(index, builderForValue.build());
        onChanged();
      } else {
        librariesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder addAllLibraries(
        java.lang.Iterable<? extends protocol_buffers.SearchedLibrary> values) {
      if (librariesBuilder_ == null) {
        ensureLibrariesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, libraries_);
        onChanged();
      } else {
        librariesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder clearLibraries() {
      if (librariesBuilder_ == null) {
        libraries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        librariesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public Builder removeLibraries(int index) {
      if (librariesBuilder_ == null) {
        ensureLibrariesIsMutable();
        libraries_.remove(index);
        onChanged();
      } else {
        librariesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public protocol_buffers.SearchedLibrary.Builder getLibrariesBuilder(
        int index) {
      return internalGetLibrariesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public protocol_buffers.SearchedLibraryOrBuilder getLibrariesOrBuilder(
        int index) {
      if (librariesBuilder_ == null) {
        return libraries_.get(index);  } else {
        return librariesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public java.util.List<? extends protocol_buffers.SearchedLibraryOrBuilder> 
         getLibrariesOrBuilderList() {
      if (librariesBuilder_ != null) {
        return librariesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(libraries_);
      }
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public protocol_buffers.SearchedLibrary.Builder addLibrariesBuilder() {
      return internalGetLibrariesFieldBuilder().addBuilder(
          protocol_buffers.SearchedLibrary.getDefaultInstance());
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public protocol_buffers.SearchedLibrary.Builder addLibrariesBuilder(
        int index) {
      return internalGetLibrariesFieldBuilder().addBuilder(
          index, protocol_buffers.SearchedLibrary.getDefaultInstance());
    }
    /**
     * <pre>
     * The results of the search.
     * </pre>
     *
     * <code>repeated .protocol_buffers.SearchedLibrary libraries = 1;</code>
     */
    public java.util.List<protocol_buffers.SearchedLibrary.Builder> 
         getLibrariesBuilderList() {
      return internalGetLibrariesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        protocol_buffers.SearchedLibrary, protocol_buffers.SearchedLibrary.Builder, protocol_buffers.SearchedLibraryOrBuilder> 
        internalGetLibrariesFieldBuilder() {
      if (librariesBuilder_ == null) {
        librariesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            protocol_buffers.SearchedLibrary, protocol_buffers.SearchedLibrary.Builder, protocol_buffers.SearchedLibraryOrBuilder>(
                libraries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        libraries_ = null;
      }
      return librariesBuilder_;
    }

    private int status_ = 0;
    /**
     * <pre>
     * Whether the search yielded results.
     * </pre>
     *
     * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Whether the search yielded results.
     * </pre>
     *
     * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the search yielded results.
     * </pre>
     *
     * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public protocol_buffers.LibrarySearchStatus getStatus() {
      protocol_buffers.LibrarySearchStatus result = protocol_buffers.LibrarySearchStatus.forNumber(status_);
      return result == null ? protocol_buffers.LibrarySearchStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Whether the search yielded results.
     * </pre>
     *
     * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(protocol_buffers.LibrarySearchStatus value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the search yielded results.
     * </pre>
     *
     * <code>.protocol_buffers.LibrarySearchStatus status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:protocol_buffers.LibrarySearchResponse)
  }

  // @@protoc_insertion_point(class_scope:protocol_buffers.LibrarySearchResponse)
  private static final protocol_buffers.LibrarySearchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol_buffers.LibrarySearchResponse();
  }

  public static protocol_buffers.LibrarySearchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LibrarySearchResponse>
      PARSER = new com.google.protobuf.AbstractParser<LibrarySearchResponse>() {
    @java.lang.Override
    public LibrarySearchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LibrarySearchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibrarySearchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol_buffers.LibrarySearchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

