// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/commands/proto/common.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public interface SketchProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol_buffers.SketchProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the profile.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the profile.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * FQBN used by the profile.
   * </pre>
   *
   * <code>string fqbn = 2;</code>
   * @return The fqbn.
   */
  java.lang.String getFqbn();
  /**
   * <pre>
   * FQBN used by the profile.
   * </pre>
   *
   * <code>string fqbn = 2;</code>
   * @return The bytes for fqbn.
   */
  com.google.protobuf.ByteString
      getFqbnBytes();

  /**
   * <pre>
   * Programmer used by the profile.
   * </pre>
   *
   * <code>string programmer = 3;</code>
   * @return The programmer.
   */
  java.lang.String getProgrammer();
  /**
   * <pre>
   * Programmer used by the profile.
   * </pre>
   *
   * <code>string programmer = 3;</code>
   * @return The bytes for programmer.
   */
  com.google.protobuf.ByteString
      getProgrammerBytes();

  /**
   * <pre>
   * Default Port in this profile.
   * </pre>
   *
   * <code>string port = 4;</code>
   * @return The port.
   */
  java.lang.String getPort();
  /**
   * <pre>
   * Default Port in this profile.
   * </pre>
   *
   * <code>string port = 4;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();

  /**
   * <pre>
   * Default Port configuration set in project file (sketch.yaml).
   * </pre>
   *
   * <code>.protocol_buffers.MonitorPortConfiguration port_config = 5;</code>
   * @return Whether the portConfig field is set.
   */
  boolean hasPortConfig();
  /**
   * <pre>
   * Default Port configuration set in project file (sketch.yaml).
   * </pre>
   *
   * <code>.protocol_buffers.MonitorPortConfiguration port_config = 5;</code>
   * @return The portConfig.
   */
  protocol_buffers.MonitorPortConfiguration getPortConfig();
  /**
   * <pre>
   * Default Port configuration set in project file (sketch.yaml).
   * </pre>
   *
   * <code>.protocol_buffers.MonitorPortConfiguration port_config = 5;</code>
   */
  protocol_buffers.MonitorPortConfigurationOrBuilder getPortConfigOrBuilder();

  /**
   * <pre>
   * Default Protocol in this profile.
   * </pre>
   *
   * <code>string protocol = 6;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   * Default Protocol in this profile.
   * </pre>
   *
   * <code>string protocol = 6;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();
}
