// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/common.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

/**
 * Protobuf type {@code protocol_buffers.DownloadProgressUpdate}
 */
@com.google.protobuf.Generated
public final class DownloadProgressUpdate extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol_buffers.DownloadProgressUpdate)
    DownloadProgressUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      DownloadProgressUpdate.class.getName());
  }
  // Use DownloadProgressUpdate.newBuilder() to construct.
  private DownloadProgressUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DownloadProgressUpdate() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protocol_buffers.Common.internal_static_protocol_buffers_DownloadProgressUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protocol_buffers.Common.internal_static_protocol_buffers_DownloadProgressUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protocol_buffers.DownloadProgressUpdate.class, protocol_buffers.DownloadProgressUpdate.Builder.class);
  }

  public static final int DOWNLOADED_FIELD_NUMBER = 1;
  private long downloaded_ = 0L;
  /**
   * <pre>
   * Size of the downloaded portion of the file.
   * </pre>
   *
   * <code>int64 downloaded = 1;</code>
   * @return The downloaded.
   */
  @java.lang.Override
  public long getDownloaded() {
    return downloaded_;
  }

  public static final int TOTAL_SIZE_FIELD_NUMBER = 2;
  private long totalSize_ = 0L;
  /**
   * <pre>
   * Total size of the file being downloaded.
   * </pre>
   *
   * <code>int64 total_size = 2;</code>
   * @return The totalSize.
   */
  @java.lang.Override
  public long getTotalSize() {
    return totalSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (downloaded_ != 0L) {
      output.writeInt64(1, downloaded_);
    }
    if (totalSize_ != 0L) {
      output.writeInt64(2, totalSize_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (downloaded_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, downloaded_);
    }
    if (totalSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protocol_buffers.DownloadProgressUpdate)) {
      return super.equals(obj);
    }
    protocol_buffers.DownloadProgressUpdate other = (protocol_buffers.DownloadProgressUpdate) obj;

    if (getDownloaded()
        != other.getDownloaded()) return false;
    if (getTotalSize()
        != other.getTotalSize()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOWNLOADED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDownloaded());
    hash = (37 * hash) + TOTAL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalSize());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static protocol_buffers.DownloadProgressUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static protocol_buffers.DownloadProgressUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static protocol_buffers.DownloadProgressUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protocol_buffers.DownloadProgressUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol_buffers.DownloadProgressUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol_buffers.DownloadProgressUpdate)
      protocol_buffers.DownloadProgressUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_buffers.Common.internal_static_protocol_buffers_DownloadProgressUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_buffers.Common.internal_static_protocol_buffers_DownloadProgressUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_buffers.DownloadProgressUpdate.class, protocol_buffers.DownloadProgressUpdate.Builder.class);
    }

    // Construct using protocol_buffers.DownloadProgressUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      downloaded_ = 0L;
      totalSize_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protocol_buffers.Common.internal_static_protocol_buffers_DownloadProgressUpdate_descriptor;
    }

    @java.lang.Override
    public protocol_buffers.DownloadProgressUpdate getDefaultInstanceForType() {
      return protocol_buffers.DownloadProgressUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public protocol_buffers.DownloadProgressUpdate build() {
      protocol_buffers.DownloadProgressUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protocol_buffers.DownloadProgressUpdate buildPartial() {
      protocol_buffers.DownloadProgressUpdate result = new protocol_buffers.DownloadProgressUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protocol_buffers.DownloadProgressUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.downloaded_ = downloaded_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalSize_ = totalSize_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protocol_buffers.DownloadProgressUpdate) {
        return mergeFrom((protocol_buffers.DownloadProgressUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protocol_buffers.DownloadProgressUpdate other) {
      if (other == protocol_buffers.DownloadProgressUpdate.getDefaultInstance()) return this;
      if (other.getDownloaded() != 0L) {
        setDownloaded(other.getDownloaded());
      }
      if (other.getTotalSize() != 0L) {
        setTotalSize(other.getTotalSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              downloaded_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              totalSize_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long downloaded_ ;
    /**
     * <pre>
     * Size of the downloaded portion of the file.
     * </pre>
     *
     * <code>int64 downloaded = 1;</code>
     * @return The downloaded.
     */
    @java.lang.Override
    public long getDownloaded() {
      return downloaded_;
    }
    /**
     * <pre>
     * Size of the downloaded portion of the file.
     * </pre>
     *
     * <code>int64 downloaded = 1;</code>
     * @param value The downloaded to set.
     * @return This builder for chaining.
     */
    public Builder setDownloaded(long value) {

      downloaded_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Size of the downloaded portion of the file.
     * </pre>
     *
     * <code>int64 downloaded = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDownloaded() {
      bitField0_ = (bitField0_ & ~0x00000001);
      downloaded_ = 0L;
      onChanged();
      return this;
    }

    private long totalSize_ ;
    /**
     * <pre>
     * Total size of the file being downloaded.
     * </pre>
     *
     * <code>int64 total_size = 2;</code>
     * @return The totalSize.
     */
    @java.lang.Override
    public long getTotalSize() {
      return totalSize_;
    }
    /**
     * <pre>
     * Total size of the file being downloaded.
     * </pre>
     *
     * <code>int64 total_size = 2;</code>
     * @param value The totalSize to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSize(long value) {

      totalSize_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total size of the file being downloaded.
     * </pre>
     *
     * <code>int64 total_size = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalSize_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:protocol_buffers.DownloadProgressUpdate)
  }

  // @@protoc_insertion_point(class_scope:protocol_buffers.DownloadProgressUpdate)
  private static final protocol_buffers.DownloadProgressUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protocol_buffers.DownloadProgressUpdate();
  }

  public static protocol_buffers.DownloadProgressUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DownloadProgressUpdate>
      PARSER = new com.google.protobuf.AbstractParser<DownloadProgressUpdate>() {
    @java.lang.Override
    public DownloadProgressUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DownloadProgressUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DownloadProgressUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protocol_buffers.DownloadProgressUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

