// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/lib.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public final class Lib {
  private Lib() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Lib.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryDownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryDownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryDownloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryDownloadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryDownloadResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryDownloadResponse_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryInstallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryInstallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryInstallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryInstallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryInstallResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryInstallResponse_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUpgradeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUpgradeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUpgradeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUpgradeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUpgradeResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUpgradeResponse_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUninstallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUninstallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUninstallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUninstallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUninstallResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUninstallResponse_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUpgradeAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUpgradeAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUpgradeAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUpgradeAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryUpgradeAllResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryUpgradeAllResponse_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryResolveDependenciesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryResolveDependenciesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryResolveDependenciesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryResolveDependenciesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryDependencyStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryDependencyStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibrarySearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibrarySearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibrarySearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibrarySearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_SearchedLibrary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_SearchedLibrary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_SearchedLibrary_ReleasesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_SearchedLibrary_ReleasesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryRelease_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryRelease_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryDependency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryDependency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_DownloadResource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_DownloadResource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_LibraryListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_LibraryListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_InstalledLibrary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_InstalledLibrary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_Library_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_Library_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_Library_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_Library_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_Library_CompatibleWithEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_Library_CompatibleWithEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_ZipLibraryInstallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_ZipLibraryInstallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_ZipLibraryInstallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_ZipLibraryInstallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_ZipLibraryInstallResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_ZipLibraryInstallResponse_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_GitLibraryInstallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_GitLibraryInstallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_GitLibraryInstallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_GitLibraryInstallResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_buffers_GitLibraryInstallResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_buffers_GitLibraryInstallResponse_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEapp/src/main/java/com/example/arduinoi" +
      "de/cli/commands/proto/lib.proto\022\020protoco" +
      "l_buffers\032Happ/src/main/java/com/example" +
      "/arduinoide/cli/commands/proto/common.pr" +
      "oto\"e\n\026LibraryDownloadRequest\022,\n\010instanc" +
      "e\030\001 \001(\0132\032.protocol_buffers.Instance\022\014\n\004n" +
      "ame\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\"\252\001\n\027LibraryDo" +
      "wnloadResponse\0226\n\010progress\030\001 \001(\0132\".proto" +
      "col_buffers.DownloadProgressH\000\022B\n\006result" +
      "\030\002 \001(\01320.protocol_buffers.LibraryDownloa" +
      "dResponse.ResultH\000\032\010\n\006ResultB\t\n\007message\"" +
      "\317\001\n\025LibraryInstallRequest\022,\n\010instance\030\001 " +
      "\001(\0132\032.protocol_buffers.Instance\022\014\n\004name\030" +
      "\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\017\n\007no_deps\030\004 \001(\010\022" +
      "\024\n\014no_overwrite\030\005 \001(\010\022B\n\020install_locatio" +
      "n\030\006 \001(\0162(.protocol_buffers.LibraryInstal" +
      "lLocation\"\341\001\n\026LibraryInstallResponse\0226\n\010" +
      "progress\030\001 \001(\0132\".protocol_buffers.Downlo" +
      "adProgressH\000\0227\n\rtask_progress\030\002 \001(\0132\036.pr" +
      "otocol_buffers.TaskProgressH\000\022A\n\006result\030" +
      "\003 \001(\0132/.protocol_buffers.LibraryInstallR" +
      "esponse.ResultH\000\032\010\n\006ResultB\t\n\007message\"d\n" +
      "\025LibraryUpgradeRequest\022,\n\010instance\030\001 \001(\013" +
      "2\032.protocol_buffers.Instance\022\014\n\004name\030\002 \001" +
      "(\t\022\017\n\007no_deps\030\003 \001(\010\"\341\001\n\026LibraryUpgradeRe" +
      "sponse\0226\n\010progress\030\001 \001(\0132\".protocol_buff" +
      "ers.DownloadProgressH\000\0227\n\rtask_progress\030" +
      "\002 \001(\0132\036.protocol_buffers.TaskProgressH\000\022" +
      "A\n\006result\030\003 \001(\0132/.protocol_buffers.Libra" +
      "ryUpgradeResponse.ResultH\000\032\010\n\006ResultB\t\n\007" +
      "message\"f\n\027LibraryUninstallRequest\022,\n\010in" +
      "stance\030\001 \001(\0132\032.protocol_buffers.Instance" +
      "\022\014\n\004name\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\"\255\001\n\030Libr" +
      "aryUninstallResponse\0227\n\rtask_progress\030\001 " +
      "\001(\0132\036.protocol_buffers.TaskProgressH\000\022C\n" +
      "\006result\030\002 \001(\01321.protocol_buffers.Library" +
      "UninstallResponse.ResultH\000\032\010\n\006ResultB\t\n\007" +
      "message\"H\n\030LibraryUpgradeAllRequest\022,\n\010i" +
      "nstance\030\001 \001(\0132\032.protocol_buffers.Instanc" +
      "e\"\347\001\n\031LibraryUpgradeAllResponse\0226\n\010progr" +
      "ess\030\001 \001(\0132\".protocol_buffers.DownloadPro" +
      "gressH\000\0227\n\rtask_progress\030\002 \001(\0132\036.protoco" +
      "l_buffers.TaskProgressH\000\022D\n\006result\030\003 \001(\013" +
      "22.protocol_buffers.LibraryUpgradeAllRes" +
      "ponse.ResultH\000\032\010\n\006ResultB\t\n\007message\"\233\001\n!" +
      "LibraryResolveDependenciesRequest\022,\n\010ins" +
      "tance\030\001 \001(\0132\032.protocol_buffers.Instance\022" +
      "\014\n\004name\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022)\n!do_not" +
      "_update_installed_libraries\030\004 \001(\010\"e\n\"Lib" +
      "raryResolveDependenciesResponse\022?\n\014depen" +
      "dencies\030\001 \003(\0132).protocol_buffers.Library" +
      "DependencyStatus\"\\\n\027LibraryDependencySta" +
      "tus\022\014\n\004name\030\001 \001(\t\022\030\n\020version_required\030\002 " +
      "\001(\t\022\031\n\021version_installed\030\003 \001(\t\"x\n\024Librar" +
      "ySearchRequest\022,\n\010instance\030\001 \001(\0132\032.proto" +
      "col_buffers.Instance\022\035\n\025omit_releases_de" +
      "tails\030\002 \001(\010\022\023\n\013search_args\030\003 \001(\t\"\204\001\n\025Lib" +
      "rarySearchResponse\0224\n\tlibraries\030\001 \003(\0132!." +
      "protocol_buffers.SearchedLibrary\0225\n\006stat" +
      "us\030\002 \001(\0162%.protocol_buffers.LibrarySearc" +
      "hStatus\"\203\002\n\017SearchedLibrary\022\014\n\004name\030\001 \001(" +
      "\t\022A\n\010releases\030\002 \003(\0132/.protocol_buffers.S" +
      "earchedLibrary.ReleasesEntry\0220\n\006latest\030\003" +
      " \001(\0132 .protocol_buffers.LibraryRelease\022\032" +
      "\n\022available_versions\030\004 \003(\t\032Q\n\rReleasesEn" +
      "try\022\013\n\003key\030\001 \001(\t\022/\n\005value\030\002 \001(\0132 .protoc" +
      "ol_buffers.LibraryRelease:\0028\001\"\321\002\n\016Librar" +
      "yRelease\022\016\n\006author\030\001 \001(\t\022\017\n\007version\030\002 \001(" +
      "\t\022\022\n\nmaintainer\030\003 \001(\t\022\020\n\010sentence\030\004 \001(\t\022" +
      "\021\n\tparagraph\030\005 \001(\t\022\017\n\007website\030\006 \001(\t\022\020\n\010c" +
      "ategory\030\007 \001(\t\022\025\n\rarchitectures\030\010 \003(\t\022\r\n\005" +
      "types\030\t \003(\t\0225\n\tresources\030\n \001(\0132\".protoco" +
      "l_buffers.DownloadResource\022\017\n\007license\030\013 " +
      "\001(\t\022\031\n\021provides_includes\030\014 \003(\t\0229\n\014depend" +
      "encies\030\r \003(\0132#.protocol_buffers.LibraryD" +
      "ependency\"=\n\021LibraryDependency\022\014\n\004name\030\001" +
      " \001(\t\022\032\n\022version_constraint\030\002 \001(\t\"m\n\020Down" +
      "loadResource\022\013\n\003url\030\001 \001(\t\022\030\n\020archive_fil" +
      "ename\030\002 \001(\t\022\020\n\010checksum\030\003 \001(\t\022\014\n\004size\030\004 " +
      "\001(\003\022\022\n\ncache_path\030\005 \001(\t\"~\n\022LibraryListRe" +
      "quest\022,\n\010instance\030\001 \001(\0132\032.protocol_buffe" +
      "rs.Instance\022\013\n\003all\030\002 \001(\010\022\021\n\tupdatable\030\003 " +
      "\001(\010\022\014\n\004name\030\004 \001(\t\022\014\n\004fqbn\030\005 \001(\t\"V\n\023Libra" +
      "ryListResponse\022?\n\023installed_libraries\030\001 " +
      "\003(\0132\".protocol_buffers.InstalledLibrary\"" +
      "q\n\020InstalledLibrary\022*\n\007library\030\001 \001(\0132\031.p" +
      "rotocol_buffers.Library\0221\n\007release\030\002 \001(\013" +
      "2 .protocol_buffers.LibraryRelease\"\222\006\n\007L" +
      "ibrary\022\014\n\004name\030\001 \001(\t\022\016\n\006author\030\002 \001(\t\022\022\n\n" +
      "maintainer\030\003 \001(\t\022\020\n\010sentence\030\004 \001(\t\022\021\n\tpa" +
      "ragraph\030\005 \001(\t\022\017\n\007website\030\006 \001(\t\022\020\n\010catego" +
      "ry\030\007 \001(\t\022\025\n\rarchitectures\030\010 \003(\t\022\r\n\005types" +
      "\030\t \003(\t\022\023\n\013install_dir\030\n \001(\t\022\022\n\nsource_di" +
      "r\030\013 \001(\t\022\023\n\013utility_dir\030\014 \001(\t\022\032\n\022containe" +
      "r_platform\030\016 \001(\t\022\025\n\rdot_a_linkage\030\021 \001(\010\022" +
      "\023\n\013precompiled\030\022 \001(\010\022\020\n\010ld_flags\030\023 \001(\t\022\021" +
      "\n\tis_legacy\030\024 \001(\010\022\017\n\007version\030\025 \001(\t\022\017\n\007li" +
      "cense\030\026 \001(\t\022=\n\nproperties\030\027 \003(\0132).protoc" +
      "ol_buffers.Library.PropertiesEntry\0223\n\010lo" +
      "cation\030\030 \001(\0162!.protocol_buffers.LibraryL" +
      "ocation\022/\n\006layout\030\031 \001(\0162\037.protocol_buffe" +
      "rs.LibraryLayout\022\020\n\010examples\030\032 \003(\t\022\031\n\021pr" +
      "ovides_includes\030\033 \003(\t\022F\n\017compatible_with" +
      "\030\034 \003(\0132-.protocol_buffers.Library.Compat" +
      "ibleWithEntry\022\026\n\016in_development\030\035 \001(\010\0321\n" +
      "\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\0325\n\023CompatibleWithEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\010:\0028\001\"i\n\030ZipLibraryIns" +
      "tallRequest\022,\n\010instance\030\001 \001(\0132\032.protocol" +
      "_buffers.Instance\022\014\n\004path\030\002 \001(\t\022\021\n\toverw" +
      "rite\030\003 \001(\010\"\257\001\n\031ZipLibraryInstallResponse" +
      "\0227\n\rtask_progress\030\001 \001(\0132\036.protocol_buffe" +
      "rs.TaskProgressH\000\022D\n\006result\030\002 \001(\01322.prot" +
      "ocol_buffers.ZipLibraryInstallResponse.R" +
      "esultH\000\032\010\n\006ResultB\t\n\007message\"h\n\030GitLibra" +
      "ryInstallRequest\022,\n\010instance\030\001 \001(\0132\032.pro" +
      "tocol_buffers.Instance\022\013\n\003url\030\002 \001(\t\022\021\n\to" +
      "verwrite\030\003 \001(\010\"\257\001\n\031GitLibraryInstallResp" +
      "onse\0227\n\rtask_progress\030\001 \001(\0132\036.protocol_b" +
      "uffers.TaskProgressH\000\022D\n\006result\030\002 \001(\01322." +
      "protocol_buffers.GitLibraryInstallRespon" +
      "se.ResultH\000\032\010\n\006ResultB\t\n\007message*a\n\026Libr" +
      "aryInstallLocation\022!\n\035LIBRARY_INSTALL_LO" +
      "CATION_USER\020\000\022$\n LIBRARY_INSTALL_LOCATIO" +
      "N_BUILTIN\020\001*Z\n\023LibrarySearchStatus\022 \n\034LI" +
      "BRARY_SEARCH_STATUS_FAILED\020\000\022!\n\035LIBRARY_" +
      "SEARCH_STATUS_SUCCESS\020\001*F\n\rLibraryLayout" +
      "\022\027\n\023LIBRARY_LAYOUT_FLAT\020\000\022\034\n\030LIBRARY_LAY" +
      "OUT_RECURSIVE\020\001*\341\001\n\017LibraryLocation\022\034\n\030L" +
      "IBRARY_LOCATION_BUILTIN\020\000\022\031\n\025LIBRARY_LOC" +
      "ATION_USER\020\001\022%\n!LIBRARY_LOCATION_PLATFOR" +
      "M_BUILTIN\020\002\0220\n,LIBRARY_LOCATION_REFERENC" +
      "ED_PLATFORM_BUILTIN\020\003\022\036\n\032LIBRARY_LOCATIO" +
      "N_UNMANAGED\020\004\022\034\n\030LIBRARY_LOCATION_PROFIL" +
      "E\020\005B\024\n\020protocol_buffersP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol_buffers.Common.getDescriptor(),
        });
    internal_static_protocol_buffers_LibraryDownloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_buffers_LibraryDownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryDownloadRequest_descriptor,
        new java.lang.String[] { "Instance", "Name", "Version", });
    internal_static_protocol_buffers_LibraryDownloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_buffers_LibraryDownloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryDownloadResponse_descriptor,
        new java.lang.String[] { "Progress", "Result", "Message", });
    internal_static_protocol_buffers_LibraryDownloadResponse_Result_descriptor =
      internal_static_protocol_buffers_LibraryDownloadResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_LibraryDownloadResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryDownloadResponse_Result_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_LibraryInstallRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_buffers_LibraryInstallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryInstallRequest_descriptor,
        new java.lang.String[] { "Instance", "Name", "Version", "NoDeps", "NoOverwrite", "InstallLocation", });
    internal_static_protocol_buffers_LibraryInstallResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_buffers_LibraryInstallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryInstallResponse_descriptor,
        new java.lang.String[] { "Progress", "TaskProgress", "Result", "Message", });
    internal_static_protocol_buffers_LibraryInstallResponse_Result_descriptor =
      internal_static_protocol_buffers_LibraryInstallResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_LibraryInstallResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryInstallResponse_Result_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_LibraryUpgradeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_buffers_LibraryUpgradeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUpgradeRequest_descriptor,
        new java.lang.String[] { "Instance", "Name", "NoDeps", });
    internal_static_protocol_buffers_LibraryUpgradeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protocol_buffers_LibraryUpgradeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUpgradeResponse_descriptor,
        new java.lang.String[] { "Progress", "TaskProgress", "Result", "Message", });
    internal_static_protocol_buffers_LibraryUpgradeResponse_Result_descriptor =
      internal_static_protocol_buffers_LibraryUpgradeResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_LibraryUpgradeResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUpgradeResponse_Result_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_LibraryUninstallRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protocol_buffers_LibraryUninstallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUninstallRequest_descriptor,
        new java.lang.String[] { "Instance", "Name", "Version", });
    internal_static_protocol_buffers_LibraryUninstallResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protocol_buffers_LibraryUninstallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUninstallResponse_descriptor,
        new java.lang.String[] { "TaskProgress", "Result", "Message", });
    internal_static_protocol_buffers_LibraryUninstallResponse_Result_descriptor =
      internal_static_protocol_buffers_LibraryUninstallResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_LibraryUninstallResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUninstallResponse_Result_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_LibraryUpgradeAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_protocol_buffers_LibraryUpgradeAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUpgradeAllRequest_descriptor,
        new java.lang.String[] { "Instance", });
    internal_static_protocol_buffers_LibraryUpgradeAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_protocol_buffers_LibraryUpgradeAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUpgradeAllResponse_descriptor,
        new java.lang.String[] { "Progress", "TaskProgress", "Result", "Message", });
    internal_static_protocol_buffers_LibraryUpgradeAllResponse_Result_descriptor =
      internal_static_protocol_buffers_LibraryUpgradeAllResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_LibraryUpgradeAllResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryUpgradeAllResponse_Result_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_LibraryResolveDependenciesRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_protocol_buffers_LibraryResolveDependenciesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryResolveDependenciesRequest_descriptor,
        new java.lang.String[] { "Instance", "Name", "Version", "DoNotUpdateInstalledLibraries", });
    internal_static_protocol_buffers_LibraryResolveDependenciesResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_protocol_buffers_LibraryResolveDependenciesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryResolveDependenciesResponse_descriptor,
        new java.lang.String[] { "Dependencies", });
    internal_static_protocol_buffers_LibraryDependencyStatus_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_protocol_buffers_LibraryDependencyStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryDependencyStatus_descriptor,
        new java.lang.String[] { "Name", "VersionRequired", "VersionInstalled", });
    internal_static_protocol_buffers_LibrarySearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_protocol_buffers_LibrarySearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibrarySearchRequest_descriptor,
        new java.lang.String[] { "Instance", "OmitReleasesDetails", "SearchArgs", });
    internal_static_protocol_buffers_LibrarySearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_protocol_buffers_LibrarySearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibrarySearchResponse_descriptor,
        new java.lang.String[] { "Libraries", "Status", });
    internal_static_protocol_buffers_SearchedLibrary_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_protocol_buffers_SearchedLibrary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_SearchedLibrary_descriptor,
        new java.lang.String[] { "Name", "Releases", "Latest", "AvailableVersions", });
    internal_static_protocol_buffers_SearchedLibrary_ReleasesEntry_descriptor =
      internal_static_protocol_buffers_SearchedLibrary_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_SearchedLibrary_ReleasesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_SearchedLibrary_ReleasesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_buffers_LibraryRelease_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_protocol_buffers_LibraryRelease_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryRelease_descriptor,
        new java.lang.String[] { "Author", "Version", "Maintainer", "Sentence", "Paragraph", "Website", "Category", "Architectures", "Types", "Resources", "License", "ProvidesIncludes", "Dependencies", });
    internal_static_protocol_buffers_LibraryDependency_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_protocol_buffers_LibraryDependency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryDependency_descriptor,
        new java.lang.String[] { "Name", "VersionConstraint", });
    internal_static_protocol_buffers_DownloadResource_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_protocol_buffers_DownloadResource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_DownloadResource_descriptor,
        new java.lang.String[] { "Url", "ArchiveFilename", "Checksum", "Size", "CachePath", });
    internal_static_protocol_buffers_LibraryListRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_protocol_buffers_LibraryListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryListRequest_descriptor,
        new java.lang.String[] { "Instance", "All", "Updatable", "Name", "Fqbn", });
    internal_static_protocol_buffers_LibraryListResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_protocol_buffers_LibraryListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_LibraryListResponse_descriptor,
        new java.lang.String[] { "InstalledLibraries", });
    internal_static_protocol_buffers_InstalledLibrary_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_protocol_buffers_InstalledLibrary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_InstalledLibrary_descriptor,
        new java.lang.String[] { "Library", "Release", });
    internal_static_protocol_buffers_Library_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_protocol_buffers_Library_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_Library_descriptor,
        new java.lang.String[] { "Name", "Author", "Maintainer", "Sentence", "Paragraph", "Website", "Category", "Architectures", "Types", "InstallDir", "SourceDir", "UtilityDir", "ContainerPlatform", "DotALinkage", "Precompiled", "LdFlags", "IsLegacy", "Version", "License", "Properties", "Location", "Layout", "Examples", "ProvidesIncludes", "CompatibleWith", "InDevelopment", });
    internal_static_protocol_buffers_Library_PropertiesEntry_descriptor =
      internal_static_protocol_buffers_Library_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_Library_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_Library_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_buffers_Library_CompatibleWithEntry_descriptor =
      internal_static_protocol_buffers_Library_descriptor.getNestedTypes().get(1);
    internal_static_protocol_buffers_Library_CompatibleWithEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_Library_CompatibleWithEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_buffers_ZipLibraryInstallRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_protocol_buffers_ZipLibraryInstallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_ZipLibraryInstallRequest_descriptor,
        new java.lang.String[] { "Instance", "Path", "Overwrite", });
    internal_static_protocol_buffers_ZipLibraryInstallResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_protocol_buffers_ZipLibraryInstallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_ZipLibraryInstallResponse_descriptor,
        new java.lang.String[] { "TaskProgress", "Result", "Message", });
    internal_static_protocol_buffers_ZipLibraryInstallResponse_Result_descriptor =
      internal_static_protocol_buffers_ZipLibraryInstallResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_ZipLibraryInstallResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_ZipLibraryInstallResponse_Result_descriptor,
        new java.lang.String[] { });
    internal_static_protocol_buffers_GitLibraryInstallRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_protocol_buffers_GitLibraryInstallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_GitLibraryInstallRequest_descriptor,
        new java.lang.String[] { "Instance", "Url", "Overwrite", });
    internal_static_protocol_buffers_GitLibraryInstallResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_protocol_buffers_GitLibraryInstallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_GitLibraryInstallResponse_descriptor,
        new java.lang.String[] { "TaskProgress", "Result", "Message", });
    internal_static_protocol_buffers_GitLibraryInstallResponse_Result_descriptor =
      internal_static_protocol_buffers_GitLibraryInstallResponse_descriptor.getNestedTypes().get(0);
    internal_static_protocol_buffers_GitLibraryInstallResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_buffers_GitLibraryInstallResponse_Result_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    protocol_buffers.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
