// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/lib.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol_buffers;

@kotlin.jvm.JvmName("-initializelibraryListResponse")
public inline fun libraryListResponse(block: protocol_buffers.LibraryListResponseKt.Dsl.() -> kotlin.Unit): protocol_buffers.LibraryListResponse =
  protocol_buffers.LibraryListResponseKt.Dsl._create(protocol_buffers.LibraryListResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol_buffers.LibraryListResponse`
 */
public object LibraryListResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol_buffers.LibraryListResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: protocol_buffers.LibraryListResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): protocol_buffers.LibraryListResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InstalledLibrariesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     */
     public val installedLibraries: com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.installedLibrariesList
      )
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     * @param value The installedLibraries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addInstalledLibraries")
    public fun com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>.add(value: protocol_buffers.InstalledLibrary) {
      _builder.addInstalledLibraries(value)
    }
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     * @param value The installedLibraries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignInstalledLibraries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>.plusAssign(value: protocol_buffers.InstalledLibrary) {
      add(value)
    }
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     * @param values The installedLibraries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllInstalledLibraries")
    public fun com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>.addAll(values: kotlin.collections.Iterable<protocol_buffers.InstalledLibrary>) {
      _builder.addAllInstalledLibraries(values)
    }
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     * @param values The installedLibraries to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllInstalledLibraries")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>.plusAssign(values: kotlin.collections.Iterable<protocol_buffers.InstalledLibrary>) {
      addAll(values)
    }
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     * @param index The index to set the value at.
     * @param value The installedLibraries to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setInstalledLibraries")
    public operator fun com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>.set(index: kotlin.Int, value: protocol_buffers.InstalledLibrary) {
      _builder.setInstalledLibraries(index, value)
    }
    /**
     * ```
     * List of installed libraries.
     * ```
     *
     * `repeated .protocol_buffers.InstalledLibrary installed_libraries = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearInstalledLibraries")
    public fun com.google.protobuf.kotlin.DslList<protocol_buffers.InstalledLibrary, InstalledLibrariesProxy>.clear() {
      _builder.clearInstalledLibraries()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol_buffers.LibraryListResponse.copy(block: `protocol_buffers`.LibraryListResponseKt.Dsl.() -> kotlin.Unit): protocol_buffers.LibraryListResponse =
  `protocol_buffers`.LibraryListResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

