// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/lib.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public interface LibraryDownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol_buffers.LibraryDownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Progress of the library download.
   * </pre>
   *
   * <code>.protocol_buffers.DownloadProgress progress = 1;</code>
   * @return Whether the progress field is set.
   */
  boolean hasProgress();
  /**
   * <pre>
   * Progress of the library download.
   * </pre>
   *
   * <code>.protocol_buffers.DownloadProgress progress = 1;</code>
   * @return The progress.
   */
  protocol_buffers.DownloadProgress getProgress();
  /**
   * <pre>
   * Progress of the library download.
   * </pre>
   *
   * <code>.protocol_buffers.DownloadProgress progress = 1;</code>
   */
  protocol_buffers.DownloadProgressOrBuilder getProgressOrBuilder();

  /**
   * <pre>
   * Download result.
   * </pre>
   *
   * <code>.protocol_buffers.LibraryDownloadResponse.Result result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   * Download result.
   * </pre>
   *
   * <code>.protocol_buffers.LibraryDownloadResponse.Result result = 2;</code>
   * @return The result.
   */
  protocol_buffers.LibraryDownloadResponse.Result getResult();
  /**
   * <pre>
   * Download result.
   * </pre>
   *
   * <code>.protocol_buffers.LibraryDownloadResponse.Result result = 2;</code>
   */
  protocol_buffers.LibraryDownloadResponse.ResultOrBuilder getResultOrBuilder();

  protocol_buffers.LibraryDownloadResponse.MessageCase getMessageCase();
}
