// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/common.proto
// Protobuf Java Version: 4.31.1

package protocol_buffers;

@com.google.protobuf.Generated
public interface PlatformMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol_buffers.PlatformMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Platform ID (e.g., `arduino:avr`).
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Platform ID (e.g., `arduino:avr`).
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Maintainer of the platform's package.
   * </pre>
   *
   * <code>string maintainer = 2;</code>
   * @return The maintainer.
   */
  java.lang.String getMaintainer();
  /**
   * <pre>
   * Maintainer of the platform's package.
   * </pre>
   *
   * <code>string maintainer = 2;</code>
   * @return The bytes for maintainer.
   */
  com.google.protobuf.ByteString
      getMaintainerBytes();

  /**
   * <pre>
   * A URL provided by the author of the platform's package, intended to point
   * to their website.
   * </pre>
   *
   * <code>string website = 3;</code>
   * @return The website.
   */
  java.lang.String getWebsite();
  /**
   * <pre>
   * A URL provided by the author of the platform's package, intended to point
   * to their website.
   * </pre>
   *
   * <code>string website = 3;</code>
   * @return The bytes for website.
   */
  com.google.protobuf.ByteString
      getWebsiteBytes();

  /**
   * <pre>
   * Email of the maintainer of the platform's package.
   * </pre>
   *
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * Email of the maintainer of the platform's package.
   * </pre>
   *
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * If true this Platform has been installed manually in the user' sketchbook
   * hardware folder.
   * </pre>
   *
   * <code>bool manually_installed = 5;</code>
   * @return The manuallyInstalled.
   */
  boolean getManuallyInstalled();

  /**
   * <pre>
   * True if the latest release of this Platform has been deprecated.
   * </pre>
   *
   * <code>bool deprecated = 6;</code>
   * @return The deprecated.
   */
  boolean getDeprecated();

  /**
   * <pre>
   * If true the platform is indexed.
   * </pre>
   *
   * <code>bool indexed = 7;</code>
   * @return The indexed.
   */
  boolean getIndexed();
}
