// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol_buffers;

@kotlin.jvm.JvmName("-initializeplatform")
public inline fun platform(block: protocol_buffers.PlatformKt.Dsl.() -> kotlin.Unit): protocol_buffers.Platform =
  protocol_buffers.PlatformKt.Dsl._create(protocol_buffers.Platform.newBuilder()).apply { block() }._build()
/**
 * ```
 * Platform is a structure containing all the information about a single
 * platform release.
 * ```
 *
 * Protobuf type `protocol_buffers.Platform`
 */
public object PlatformKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol_buffers.Platform.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: protocol_buffers.Platform.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): protocol_buffers.Platform = _builder.build()

    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.protocol_buffers.PlatformMetadata metadata = 1;`
     */
    public var metadata: protocol_buffers.PlatformMetadata
      @kotlin.jvm.JvmName("getMetadata")
        get() = _builder.metadata
      @kotlin.jvm.JvmName("setMetadata")
        set(value) {
        _builder.metadata = value
      }
    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.protocol_buffers.PlatformMetadata metadata = 1;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * Generic information about a platform.
     * ```
     *
     * `.protocol_buffers.PlatformMetadata metadata = 1;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    public val PlatformKt.Dsl.metadataOrNull: protocol_buffers.PlatformMetadata?
      get() = _builder.metadataOrNull

    /**
     * ```
     * Information about a specific release of a platform.
     * ```
     *
     * `.protocol_buffers.PlatformRelease release = 2;`
     */
    public var release: protocol_buffers.PlatformRelease
      @kotlin.jvm.JvmName("getRelease")
        get() = _builder.release
      @kotlin.jvm.JvmName("setRelease")
        set(value) {
        _builder.release = value
      }
    /**
     * ```
     * Information about a specific release of a platform.
     * ```
     *
     * `.protocol_buffers.PlatformRelease release = 2;`
     */
    public fun clearRelease() {
      _builder.clearRelease()
    }
    /**
     * ```
     * Information about a specific release of a platform.
     * ```
     *
     * `.protocol_buffers.PlatformRelease release = 2;`
     * @return Whether the release field is set.
     */
    public fun hasRelease(): kotlin.Boolean {
      return _builder.hasRelease()
    }

    public val PlatformKt.Dsl.releaseOrNull: protocol_buffers.PlatformRelease?
      get() = _builder.releaseOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol_buffers.Platform.copy(block: `protocol_buffers`.PlatformKt.Dsl.() -> kotlin.Unit): protocol_buffers.Platform =
  `protocol_buffers`.PlatformKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol_buffers.PlatformOrBuilder.metadataOrNull: protocol_buffers.PlatformMetadata?
  get() = if (hasMetadata()) getMetadata() else null

public val protocol_buffers.PlatformOrBuilder.releaseOrNull: protocol_buffers.PlatformRelease?
  get() = if (hasRelease()) getRelease() else null

