// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/lib.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol_buffers;

@kotlin.jvm.JvmName("-initializesearchedLibrary")
public inline fun searchedLibrary(block: protocol_buffers.SearchedLibraryKt.Dsl.() -> kotlin.Unit): protocol_buffers.SearchedLibrary =
  protocol_buffers.SearchedLibraryKt.Dsl._create(protocol_buffers.SearchedLibrary.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol_buffers.SearchedLibrary`
 */
public object SearchedLibraryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol_buffers.SearchedLibrary.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: protocol_buffers.SearchedLibrary.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): protocol_buffers.SearchedLibrary = _builder.build()

    /**
     * ```
     * Library name.
     * ```
     *
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * Library name.
     * ```
     *
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReleasesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The index data for the available versions of the library. The key of the
     * map is the library version.
     * ```
     *
     * `map<string, .protocol_buffers.LibraryRelease> releases = 2;`
     */
     public val releases: com.google.protobuf.kotlin.DslMap<kotlin.String, protocol_buffers.LibraryRelease, ReleasesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getReleasesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.releasesMap
      )
    /**
     * ```
     * The index data for the available versions of the library. The key of the
     * map is the library version.
     * ```
     *
     * `map<string, .protocol_buffers.LibraryRelease> releases = 2;`
     */
    @kotlin.jvm.JvmName("putReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, protocol_buffers.LibraryRelease, ReleasesProxy>
      .put(key: kotlin.String, value: protocol_buffers.LibraryRelease) {
         _builder.putReleases(key, value)
       }
    /**
     * ```
     * The index data for the available versions of the library. The key of the
     * map is the library version.
     * ```
     *
     * `map<string, .protocol_buffers.LibraryRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setReleases")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, protocol_buffers.LibraryRelease, ReleasesProxy>
      .set(key: kotlin.String, value: protocol_buffers.LibraryRelease) {
         put(key, value)
       }
    /**
     * ```
     * The index data for the available versions of the library. The key of the
     * map is the library version.
     * ```
     *
     * `map<string, .protocol_buffers.LibraryRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, protocol_buffers.LibraryRelease, ReleasesProxy>
      .remove(key: kotlin.String) {
         _builder.removeReleases(key)
       }
    /**
     * ```
     * The index data for the available versions of the library. The key of the
     * map is the library version.
     * ```
     *
     * `map<string, .protocol_buffers.LibraryRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, protocol_buffers.LibraryRelease, ReleasesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, protocol_buffers.LibraryRelease>) {
         _builder.putAllReleases(map)
       }
    /**
     * ```
     * The index data for the available versions of the library. The key of the
     * map is the library version.
     * ```
     *
     * `map<string, .protocol_buffers.LibraryRelease> releases = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearReleases")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, protocol_buffers.LibraryRelease, ReleasesProxy>
      .clear() {
         _builder.clearReleases()
       }

    /**
     * ```
     * The index data for the latest version of the library.
     * ```
     *
     * `.protocol_buffers.LibraryRelease latest = 3;`
     */
    public var latest: protocol_buffers.LibraryRelease
      @kotlin.jvm.JvmName("getLatest")
        get() = _builder.latest
      @kotlin.jvm.JvmName("setLatest")
        set(value) {
        _builder.latest = value
      }
    /**
     * ```
     * The index data for the latest version of the library.
     * ```
     *
     * `.protocol_buffers.LibraryRelease latest = 3;`
     */
    public fun clearLatest() {
      _builder.clearLatest()
    }
    /**
     * ```
     * The index data for the latest version of the library.
     * ```
     *
     * `.protocol_buffers.LibraryRelease latest = 3;`
     * @return Whether the latest field is set.
     */
    public fun hasLatest(): kotlin.Boolean {
      return _builder.hasLatest()
    }

    public val SearchedLibraryKt.Dsl.latestOrNull: protocol_buffers.LibraryRelease?
      get() = _builder.latestOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AvailableVersionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     * @return A list containing the availableVersions.
     */
    public val availableVersions: com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.availableVersionsList
      )
    /**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     * @param value The availableVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAvailableVersions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>.add(value: kotlin.String) {
      _builder.addAvailableVersions(value)
    }
    /**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     * @param value The availableVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAvailableVersions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     * @param values The availableVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAvailableVersions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllAvailableVersions(values)
    }
    /**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     * @param values The availableVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAvailableVersions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     * @param index The index to set the value at.
     * @param value The availableVersions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAvailableVersions")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setAvailableVersions(index, value)
    }/**
     * ```
     * The available versions of this library.
     * ```
     *
     * `repeated string available_versions = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAvailableVersions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, AvailableVersionsProxy>.clear() {
      _builder.clearAvailableVersions()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol_buffers.SearchedLibrary.copy(block: `protocol_buffers`.SearchedLibraryKt.Dsl.() -> kotlin.Unit): protocol_buffers.SearchedLibrary =
  `protocol_buffers`.SearchedLibraryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protocol_buffers.SearchedLibraryOrBuilder.latestOrNull: protocol_buffers.LibraryRelease?
  get() = if (hasLatest()) getLatest() else null

