// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/cli/commands/proto/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protocol_buffers;

@kotlin.jvm.JvmName("-initializetaskProgress")
public inline fun taskProgress(block: protocol_buffers.TaskProgressKt.Dsl.() -> kotlin.Unit): protocol_buffers.TaskProgress =
  protocol_buffers.TaskProgressKt.Dsl._create(protocol_buffers.TaskProgress.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protocol_buffers.TaskProgress`
 */
public object TaskProgressKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protocol_buffers.TaskProgress.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: protocol_buffers.TaskProgress.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): protocol_buffers.TaskProgress = _builder.build()

    /**
     * ```
     * Description of the task.
     * ```
     *
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * Description of the task.
     * ```
     *
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * Additional information about the task.
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * Additional information about the task.
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * ```
     * Whether the task is complete.
     * ```
     *
     * `bool completed = 3;`
     */
    public var completed: kotlin.Boolean
      @kotlin.jvm.JvmName("getCompleted")
        get() = _builder.completed
      @kotlin.jvm.JvmName("setCompleted")
        set(value) {
        _builder.completed = value
      }
    /**
     * ```
     * Whether the task is complete.
     * ```
     *
     * `bool completed = 3;`
     */
    public fun clearCompleted() {
      _builder.clearCompleted()
    }

    /**
     * ```
     * Amount in percent of the task completion (optional).
     * ```
     *
     * `float percent = 4;`
     */
    public var percent: kotlin.Float
      @kotlin.jvm.JvmName("getPercent")
        get() = _builder.percent
      @kotlin.jvm.JvmName("setPercent")
        set(value) {
        _builder.percent = value
      }
    /**
     * ```
     * Amount in percent of the task completion (optional).
     * ```
     *
     * `float percent = 4;`
     */
    public fun clearPercent() {
      _builder.clearPercent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protocol_buffers.TaskProgress.copy(block: `protocol_buffers`.TaskProgressKt.Dsl.() -> kotlin.Unit): protocol_buffers.TaskProgress =
  `protocol_buffers`.TaskProgressKt.Dsl._create(this.toBuilder()).apply { block() }._build()

