// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/cli/proto/compile.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.arduinoide.data.cli.protocol_buffers;

@kotlin.jvm.JvmName("-initializecompileResponse")
public inline fun compileResponse(block: com.example.arduinoide.data.cli.protocol_buffers.CompileResponseKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse =
  com.example.arduinoide.data.cli.protocol_buffers.CompileResponseKt.Dsl._create(com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.arduinoide.data.cli.protocol_buffers.CompileResponse`
 */
public object CompileResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse = _builder.build()

    /**
     * ```
     * The output of the compilation process (stream).
     * ```
     *
     * `bytes out_stream = 1;`
     */
    public var outStream: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getOutStream")
        get() = _builder.outStream
      @kotlin.jvm.JvmName("setOutStream")
        set(value) {
        _builder.outStream = value
      }
    /**
     * ```
     * The output of the compilation process (stream).
     * ```
     *
     * `bytes out_stream = 1;`
     */
    public fun clearOutStream() {
      _builder.clearOutStream()
    }
    /**
     * ```
     * The output of the compilation process (stream).
     * ```
     *
     * `bytes out_stream = 1;`
     * @return Whether the outStream field is set.
     */
    public fun hasOutStream(): kotlin.Boolean {
      return _builder.hasOutStream()
    }

    /**
     * ```
     * The error output of the compilation process (stream).
     * ```
     *
     * `bytes err_stream = 2;`
     */
    public var errStream: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getErrStream")
        get() = _builder.errStream
      @kotlin.jvm.JvmName("setErrStream")
        set(value) {
        _builder.errStream = value
      }
    /**
     * ```
     * The error output of the compilation process (stream).
     * ```
     *
     * `bytes err_stream = 2;`
     */
    public fun clearErrStream() {
      _builder.clearErrStream()
    }
    /**
     * ```
     * The error output of the compilation process (stream).
     * ```
     *
     * `bytes err_stream = 2;`
     * @return Whether the errStream field is set.
     */
    public fun hasErrStream(): kotlin.Boolean {
      return _builder.hasErrStream()
    }

    /**
     * ```
     * Completions reports of the compilation process (stream).
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.TaskProgress progress = 3;`
     */
    public var progress: com.example.arduinoide.data.cli.protocol_buffers.Common.TaskProgress
      @kotlin.jvm.JvmName("getProgress")
        get() = _builder.progress
      @kotlin.jvm.JvmName("setProgress")
        set(value) {
        _builder.progress = value
      }
    /**
     * ```
     * Completions reports of the compilation process (stream).
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.TaskProgress progress = 3;`
     */
    public fun clearProgress() {
      _builder.clearProgress()
    }
    /**
     * ```
     * Completions reports of the compilation process (stream).
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.TaskProgress progress = 3;`
     * @return Whether the progress field is set.
     */
    public fun hasProgress(): kotlin.Boolean {
      return _builder.hasProgress()
    }

    /**
     * ```
     * The compilation result.
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.BuilderResult result = 4;`
     */
    public var result: com.example.arduinoide.data.cli.protocol_buffers.Compile.BuilderResult
      @kotlin.jvm.JvmName("getResult")
        get() = _builder.result
      @kotlin.jvm.JvmName("setResult")
        set(value) {
        _builder.result = value
      }
    /**
     * ```
     * The compilation result.
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.BuilderResult result = 4;`
     */
    public fun clearResult() {
      _builder.clearResult()
    }
    /**
     * ```
     * The compilation result.
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.BuilderResult result = 4;`
     * @return Whether the result field is set.
     */
    public fun hasResult(): kotlin.Boolean {
      return _builder.hasResult()
    }
    public val messageCase: com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse.MessageCase
    @kotlin.jvm.JvmName("getMessageCase")
      get() = _builder.getMessageCase()

    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse.copy(block: `com.example.arduinoide.data.cli.protocol_buffers`.CompileResponseKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponse =
  `com.example.arduinoide.data.cli.protocol_buffers`.CompileResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponseOrBuilder.progressOrNull: com.example.arduinoide.data.cli.protocol_buffers.Common.TaskProgress?
  get() = if (hasProgress()) getProgress() else null

public val com.example.arduinoide.data.cli.protocol_buffers.Compile.CompileResponseOrBuilder.resultOrNull: com.example.arduinoide.data.cli.protocol_buffers.Compile.BuilderResult?
  get() = if (hasResult()) getResult() else null

