// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/cli/proto/settings.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.arduinoide.data.cli.protocol_buffers;

@kotlin.jvm.JvmName("-initializeconfigurationOpenRequest")
public inline fun configurationOpenRequest(block: com.example.arduinoide.data.cli.protocol_buffers.ConfigurationOpenRequestKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest =
  com.example.arduinoide.data.cli.protocol_buffers.ConfigurationOpenRequestKt.Dsl._create(com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.arduinoide.data.cli.protocol_buffers.ConfigurationOpenRequest`
 */
public object ConfigurationOpenRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest = _builder.build()

    /**
     * ```
     * The encoded settings.
     * ```
     *
     * `string encoded_settings = 1;`
     */
    public var encodedSettings: kotlin.String
      @kotlin.jvm.JvmName("getEncodedSettings")
        get() = _builder.encodedSettings
      @kotlin.jvm.JvmName("setEncodedSettings")
        set(value) {
        _builder.encodedSettings = value
      }
    /**
     * ```
     * The encoded settings.
     * ```
     *
     * `string encoded_settings = 1;`
     */
    public fun clearEncodedSettings() {
      _builder.clearEncodedSettings()
    }

    /**
     * ```
     * The format of the encoded settings, allowed values are "json" and "yaml".
     * ```
     *
     * `string settings_format = 2;`
     */
    public var settingsFormat: kotlin.String
      @kotlin.jvm.JvmName("getSettingsFormat")
        get() = _builder.settingsFormat
      @kotlin.jvm.JvmName("setSettingsFormat")
        set(value) {
        _builder.settingsFormat = value
      }
    /**
     * ```
     * The format of the encoded settings, allowed values are "json" and "yaml".
     * ```
     *
     * `string settings_format = 2;`
     */
    public fun clearSettingsFormat() {
      _builder.clearSettingsFormat()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest.copy(block: `com.example.arduinoide.data.cli.protocol_buffers`.ConfigurationOpenRequestKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Settings.ConfigurationOpenRequest =
  `com.example.arduinoide.data.cli.protocol_buffers`.ConfigurationOpenRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

