// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/cli/proto/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.arduinoide.data.cli.protocol_buffers;

@kotlin.jvm.JvmName("-initializeinstance")
public inline fun instance(block: com.example.arduinoide.data.cli.protocol_buffers.InstanceKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Common.Instance =
  com.example.arduinoide.data.cli.protocol_buffers.InstanceKt.Dsl._create(com.example.arduinoide.data.cli.protocol_buffers.Common.Instance.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.arduinoide.data.cli.protocol_buffers.Instance`
 */
public object InstanceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.arduinoide.data.cli.protocol_buffers.Common.Instance.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.arduinoide.data.cli.protocol_buffers.Common.Instance.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.arduinoide.data.cli.protocol_buffers.Common.Instance = _builder.build()

    /**
     * ```
     * The ID of the instance.
     * ```
     *
     * `int32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * The ID of the instance.
     * ```
     *
     * `int32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.arduinoide.data.cli.protocol_buffers.Common.Instance.copy(block: `com.example.arduinoide.data.cli.protocol_buffers`.InstanceKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Common.Instance =
  `com.example.arduinoide.data.cli.protocol_buffers`.InstanceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

