// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app/src/main/java/com/example/arduinoide/data/cli/proto/core.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.arduinoide.data.cli.protocol_buffers;

@kotlin.jvm.JvmName("-initializeplatformSearchRequest")
public inline fun platformSearchRequest(block: com.example.arduinoide.data.cli.protocol_buffers.PlatformSearchRequestKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest =
  com.example.arduinoide.data.cli.protocol_buffers.PlatformSearchRequestKt.Dsl._create(com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.arduinoide.data.cli.protocol_buffers.PlatformSearchRequest`
 */
public object PlatformSearchRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest = _builder.build()

    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.Instance instance = 1;`
     */
    public var instance: com.example.arduinoide.data.cli.protocol_buffers.Common.Instance
      @kotlin.jvm.JvmName("getInstance")
        get() = _builder.instance
      @kotlin.jvm.JvmName("setInstance")
        set(value) {
        _builder.instance = value
      }
    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.Instance instance = 1;`
     */
    public fun clearInstance() {
      _builder.clearInstance()
    }
    /**
     * ```
     * Arduino Core Service instance from the `Init` response.
     * ```
     *
     * `.com.example.arduinoide.data.cli.protocol_buffers.Instance instance = 1;`
     * @return Whether the instance field is set.
     */
    public fun hasInstance(): kotlin.Boolean {
      return _builder.hasInstance()
    }

    public val PlatformSearchRequestKt.Dsl.instanceOrNull: com.example.arduinoide.data.cli.protocol_buffers.Common.Instance?
      get() = _builder.instanceOrNull

    /**
     * ```
     * Keywords for the search.
     * ```
     *
     * `string search_args = 2;`
     */
    public var searchArgs: kotlin.String
      @kotlin.jvm.JvmName("getSearchArgs")
        get() = _builder.searchArgs
      @kotlin.jvm.JvmName("setSearchArgs")
        set(value) {
        _builder.searchArgs = value
      }
    /**
     * ```
     * Keywords for the search.
     * ```
     *
     * `string search_args = 2;`
     */
    public fun clearSearchArgs() {
      _builder.clearSearchArgs()
    }

    /**
     * ```
     * Whether to show manually installed platforms. `false` causes to skip
     * manually installed platforms.
     * ```
     *
     * `bool manually_installed = 3;`
     */
    public var manuallyInstalled: kotlin.Boolean
      @kotlin.jvm.JvmName("getManuallyInstalled")
        get() = _builder.manuallyInstalled
      @kotlin.jvm.JvmName("setManuallyInstalled")
        set(value) {
        _builder.manuallyInstalled = value
      }
    /**
     * ```
     * Whether to show manually installed platforms. `false` causes to skip
     * manually installed platforms.
     * ```
     *
     * `bool manually_installed = 3;`
     */
    public fun clearManuallyInstalled() {
      _builder.clearManuallyInstalled()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest.copy(block: `com.example.arduinoide.data.cli.protocol_buffers`.PlatformSearchRequestKt.Dsl.() -> kotlin.Unit): com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequest =
  `com.example.arduinoide.data.cli.protocol_buffers`.PlatformSearchRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.arduinoide.data.cli.protocol_buffers.Core.PlatformSearchRequestOrBuilder.instanceOrNull: com.example.arduinoide.data.cli.protocol_buffers.Common.Instance?
  get() = if (hasInstance()) getInstance() else null

